// The anti-corruption re-export: the UI's domain vocabulary. UI packages import DTO types from here,
// never from the generated api-client. This module is the only place outside the seam allowed to name
// api-client for its data-transfer types.
export type {
  CollectionEntry,
  CollectionItemInput,
  CollectionProgressDetail,
  CollectionSectionView,
  CollectionSummary,
  CollectionWriteInput,
  ContentAdminSummary,
  ContentDetail,
  ContentRevisionSummary,
  ContentSummary,
  ContentWriteInput,
  FaqEntry,
  FaqEntryWriteInput,
  FeedbackBoardItem,
  FeedbackBoardList,
  FeedbackStatus,
  FeedbackSubmission,
  FeedbackSubmissionList,
  FeedbackType,
  HelpTopic,
  HelpTopicWriteInput,
  MediaUploadRequestKind,
  NpsAnalytics,
  NpsEligibility,
  NpsResponseInput,
  NpsResponseList,
  NpsResponseView,
  NpsSubmitResult,
  NpsTrendPoint,
  ProgressSummary,
  ReviewSummary,
  SearchCatalogueType,
  SkillMastery,
  SubmitFeedbackInput,
  UpdateFeedbackInput,
} from '@TheY2T/tmr-api-client';
