import { type FlagKey, FlagKeys } from '@TheY2T/tmr-flags';

/**
 * Maps every typed flag key to its camelCase field on `Astro.locals.flags`. This is the **single wiring
 * point** for web flag consumption: the `Flags` type derives from it and the middleware builds
 * `locals.flags` by iterating it — so adding a code flag is a one-line change here (no more three parallel
 * hand-maintained lists). The field names are bespoke/historical (e.g. `platform.i18n` → `i18nEnabled`,
 * `learning.dashboard` → `learnerDashboard`, `trainers.srs` → `trainers`), so the mapping is explicit.
 * `satisfies Record<FlagKey, string>` makes it exhaustive — a new key won't compile until it's mapped.
 */
export const FLAG_FIELD_BY_KEY = {
  [FlagKeys.DemoNewBanner]: 'demoNewBanner',
  [FlagKeys.AuthEnabled]: 'authEnabled',
  [FlagKeys.AuthSignup]: 'authSignup',
  [FlagKeys.AuthSocial]: 'authSocial',
  [FlagKeys.AuthFacebook]: 'authFacebook',
  [FlagKeys.AuthMicrosoft]: 'authMicrosoft',
  [FlagKeys.AuthMicrosoftWork]: 'authMicrosoftWork',
  [FlagKeys.AuthWhatsapp]: 'authWhatsapp',
  [FlagKeys.AuthApple]: 'authApple',
  [FlagKeys.AdminCms]: 'adminCms',
  [FlagKeys.BlockEditor]: 'blockEditor',
  [FlagKeys.BlockEditorPreview]: 'blockEditorPreview',
  [FlagKeys.ContentRevisions]: 'contentRevisions',
  [FlagKeys.Favorites]: 'favorites',
  [FlagKeys.SavedProgressions]: 'savedProgressions',
  [FlagKeys.CatalogueHub]: 'catalogueHub',
  [FlagKeys.LearnerDashboard]: 'learnerDashboard',
  [FlagKeys.DashboardBackground]: 'dashboardBackground',
  [FlagKeys.Achievements]: 'achievements',
  [FlagKeys.Collections]: 'collections',
  [FlagKeys.CollectionDiscovery]: 'collectionDiscovery',
  [FlagKeys.CollectionsHub]: 'collectionsHub',
  [FlagKeys.CollectionBookmarks]: 'collectionBookmarks',
  [FlagKeys.CollectionRatings]: 'collectionRatings',
  [FlagKeys.UserCollections]: 'userCollections',
  [FlagKeys.Progress]: 'progress',
  [FlagKeys.ToolPractice]: 'toolPractice',
  [FlagKeys.InfoView]: 'infoView',
  [FlagKeys.InteractiveScores]: 'interactiveScores',
  [FlagKeys.ToolKeyboard]: 'toolKeyboard',
  [FlagKeys.ToolCircleOfFifths]: 'toolCircleOfFifths',
  [FlagKeys.ToolFretboard]: 'toolFretboard',
  [FlagKeys.ToolChords]: 'toolChords',
  [FlagKeys.ToolScaleExplorer]: 'toolScaleExplorer',
  [FlagKeys.ToolChordId]: 'toolChordId',
  [FlagKeys.ToolModes]: 'toolModes',
  [FlagKeys.ToolProgression]: 'toolProgression',
  [FlagKeys.ToolMetronome]: 'toolMetronome',
  [FlagKeys.ToolTuner]: 'toolTuner',
  [FlagKeys.ToolIntervals]: 'toolIntervals',
  [FlagKeys.ToolStaff]: 'toolStaff',
  [FlagKeys.ToolEarTrainer]: 'toolEarTrainer',
  [FlagKeys.ToolSequencer]: 'toolSequencer',
  [FlagKeys.Trainers]: 'trainers',
  [FlagKeys.DrillEngine]: 'drillEngine',
  [FlagKeys.DrillCelebrations]: 'drillCelebrations',
  [FlagKeys.DrillPlay]: 'drillPlay',
  [FlagKeys.DrillEar]: 'drillEar',
  [FlagKeys.DrillPitch]: 'drillPitch',
  [FlagKeys.DrillRhythm]: 'drillRhythm',
  [FlagKeys.ToolSightReading]: 'toolSightReading',
  [FlagKeys.ToolBackingTrack]: 'toolBackingTrack',
  [FlagKeys.ToolVoicings]: 'toolVoicings',
  [FlagKeys.ToolNotationPlayer]: 'toolNotationPlayer',
  [FlagKeys.ToolLicks]: 'toolLicks',
  [FlagKeys.ToolChordDiagrams]: 'toolChordDiagrams',
  [FlagKeys.ToolChordDictionary]: 'toolChordDictionary',
  [FlagKeys.ToolStrumming]: 'toolStrumming',
  [FlagKeys.ToolFingerpicking]: 'toolFingerpicking',
  [FlagKeys.ToolArpeggio]: 'toolArpeggio',
  [FlagKeys.ToolProgressionPlayer]: 'toolProgressionPlayer',
  [FlagKeys.ToolRhythm]: 'toolRhythm',
  [FlagKeys.ToolCaged]: 'toolCaged',
  [FlagKeys.ToolScaleBoxes]: 'toolScaleBoxes',
  [FlagKeys.ToolSong]: 'toolSong',
  [FlagKeys.ToolProgressionEar]: 'toolProgressionEar',
  [FlagKeys.ToolChordQualityEar]: 'toolChordQualityEar',
  [FlagKeys.ToolFretQuiz]: 'toolFretQuiz',
  [FlagKeys.ToolMusicXml]: 'toolMusicXml',
  [FlagKeys.ToolMultiVoice]: 'toolMultiVoice',
  [FlagKeys.ToolPracticePlayer]: 'toolPracticePlayer',
  [FlagKeys.ToolAnalyzer]: 'toolAnalyzer',
  [FlagKeys.ToolTransposer]: 'toolTransposer',
  [FlagKeys.ToolBassline]: 'toolBassline',
  [FlagKeys.ToolMelodicDictation]: 'toolMelodicDictation',
  [FlagKeys.ToolRhythmDictation]: 'toolRhythmDictation',
  [FlagKeys.ToolGrooves]: 'toolGrooves',
  [FlagKeys.ToolSolfege]: 'toolSolfege',
  [FlagKeys.ToolKeyQuiz]: 'toolKeyQuiz',
  [FlagKeys.ToolIntervalQuiz]: 'toolIntervalQuiz',
  [FlagKeys.ToolPracticeRoom]: 'toolPracticeRoom',
  [FlagKeys.ToolScore]: 'toolScore',
  [FlagKeys.ToolSoundfont]: 'toolSoundfont',
  [FlagKeys.ToolImprovise]: 'toolImprovise',
  [FlagKeys.ToolProgressionGen]: 'toolProgressionGen',
  [FlagKeys.ToolFretGame]: 'toolFretGame',
  [FlagKeys.ToolScaleMap]: 'toolScaleMap',
  [FlagKeys.ToolStaffGame]: 'toolStaffGame',
  [FlagKeys.ToolRhythmGame]: 'toolRhythmGame',
  [FlagKeys.ToolVoiceLeading]: 'toolVoiceLeading',
  [FlagKeys.ToolSpeedTrainer]: 'toolSpeedTrainer',
  [FlagKeys.ToolKeySigGame]: 'toolKeySigGame',
  [FlagKeys.ToolPracticePlanner]: 'toolPracticePlanner',
  [FlagKeys.Premium]: 'premium',
  [FlagKeys.MonetizationMessaging]: 'monetizationMessaging',
  [FlagKeys.Classrooms]: 'classrooms',
  [FlagKeys.Support]: 'support',
  [FlagKeys.ContentFaq]: 'faq',
  [FlagKeys.I18n]: 'i18nEnabled',
  [FlagKeys.LocaleStrings]: 'localeStrings',
  [FlagKeys.FeatureFlags]: 'featureFlags',
  [FlagKeys.FeedbackForm]: 'feedbackForm',
  [FlagKeys.FeedbackLauncher]: 'feedbackLauncher',
  [FlagKeys.FeedbackBugs]: 'feedbackBugs',
  [FlagKeys.FeedbackNps]: 'feedbackNps',
  [FlagKeys.FeedbackBoard]: 'feedbackBoard',
} as const satisfies Record<FlagKey, string>;

/** The camelCase field names on `Flags` (derived from the map values). */
export type FlagField = (typeof FLAG_FIELD_BY_KEY)[FlagKey];

/**
 * Feature-flag values evaluated once per request in the web middleware (see apps/web/src/middleware.ts).
 * Derived from {@link FLAG_FIELD_BY_KEY} so the shape can never drift from the typed registry.
 */
export type Flags = Record<FlagField, boolean>;
