import {
  ArrowLeft,
  ArrowRight,
  BarChart3,
  Bold,
  Bookmark,
  BookmarkCheck,
  BookOpen,
  Calendar,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleCheck,
  Clock,
  Code,
  Compass,
  Copy,
  Crown,
  Disc3,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  Filter,
  Flame,
  Folder,
  Gauge,
  Globe,
  GraduationCap,
  GripVertical,
  Guitar,
  Heading2,
  Headphones,
  Heart,
  Info,
  Italic,
  LayoutGrid,
  Library,
  Link as LinkIcon,
  List,
  ListMusic,
  ListOrdered,
  LoaderCircle,
  Lock,
  LogIn,
  LogOut,
  type LucideProps,
  Maximize2,
  Menu,
  Mic,
  Minimize2,
  Minus,
  Moon,
  MoreHorizontal,
  Music,
  Palette,
  PartyPopper,
  Pause,
  Pencil,
  Piano,
  Play,
  Plus,
  Quote,
  Redo2,
  RefreshCw,
  Repeat,
  Search,
  Settings,
  Signpost,
  SkipBack,
  SlidersHorizontal,
  Sparkles,
  Square,
  Star,
  Strikethrough,
  Sun,
  Table as TableIcon,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Undo2,
  Upload,
  User,
  Users,
  Volume2,
  Wrench,
  X,
} from 'lucide-react';
import { cn } from '../../lib/utils';

/**
 * Curated icon registry (Lucide). Direct named imports so only registered icons ship — a
 * `import * as` / dynamic-by-name lookup would defeat tree-shaking and pull the whole library.
 * To add an icon: import it from `lucide-react` and add a kebab-case entry here (ADR 0019).
 */
const registry = {
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  bookmark: Bookmark,
  'bookmark-check': BookmarkCheck,
  'book-open': BookOpen,
  calendar: Calendar,
  chart: BarChart3,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  circle: Circle,
  'circle-check': CircleCheck,
  clock: Clock,
  compass: Compass,
  copy: Copy,
  crown: Crown,
  disc: Disc3,
  download: Download,
  'external-link': ExternalLink,
  eye: Eye,
  'eye-off': EyeOff,
  filter: Filter,
  flame: Flame,
  folder: Folder,
  gauge: Gauge,
  globe: Globe,
  'graduation-cap': GraduationCap,
  'grip-vertical': GripVertical,
  guitar: Guitar,
  headphones: Headphones,
  heart: Heart,
  info: Info,
  'layout-grid': LayoutGrid,
  library: Library,
  'list-music': ListMusic,
  loader: LoaderCircle,
  lock: Lock,
  'log-in': LogIn,
  'log-out': LogOut,
  maximize: Maximize2,
  menu: Menu,
  mic: Mic,
  minimize: Minimize2,
  moon: Moon,
  music: Music,
  palette: Palette,
  'party-popper': PartyPopper,
  pencil: Pencil,
  piano: Piano,
  pause: Pause,
  play: Play,
  plus: Plus,
  refresh: RefreshCw,
  repeat: Repeat,
  'skip-back': SkipBack,
  search: Search,
  settings: Settings,
  signpost: Signpost,
  sliders: SlidersHorizontal,
  sparkles: Sparkles,
  square: Square,
  star: Star,
  sun: Sun,
  trash: Trash2,
  'trending-up': TrendingUp,
  'alert-triangle': TriangleAlert,
  upload: Upload,
  user: User,
  users: Users,
  volume: Volume2,
  wrench: Wrench,
  x: X,
  bold: Bold,
  code: Code,
  'heading-2': Heading2,
  italic: Italic,
  link: LinkIcon,
  list: List,
  'list-ordered': ListOrdered,
  minus: Minus,
  'more-horizontal': MoreHorizontal,
  quote: Quote,
  redo: Redo2,
  strikethrough: Strikethrough,
  table: TableIcon,
  undo: Undo2,
} as const;

export type IconName = keyof typeof registry;

export interface IconProps extends Omit<LucideProps, 'ref'> {
  /** Registered icon name (see the registry above). */
  name: IconName;
  /**
   * Already-localized accessible name. Omit for decorative icons (the common case) — the icon is
   * then hidden from assistive tech. Pass a translated string (from the app's `t()`, never inside
   * the library) only when the icon carries meaning on its own. ADR 0017 / ADR 0019.
   */
  label?: string;
}

/**
 * The single sanctioned way to render an icon in React islands. Size + color via Tailwind on
 * `className` (`size-4`, `text-muted-foreground`); Lucide uses `currentColor` so `text-*` just works.
 */
export function Icon({ name, label, className, ...props }: IconProps) {
  const Glyph = registry[name];
  return (
    <Glyph
      className={cn('shrink-0', className)}
      aria-hidden={label ? undefined : true}
      aria-label={label}
      role={label ? 'img' : undefined}
      focusable="false"
      {...props}
    />
  );
}
