import type { Specimen } from './types';

// App-shell chrome, dashboards + widgets, account/auth/billing, feedback/NPS, and the admin CMS. Most
// take just `locale` (supplied by the stage). Data-backed ones (health, home, dashboards, admin
// managers) read the mock port / hit the API and render their loading/empty states offline.
const ex = () => import('@/examples/common-ui-examples');

export const commonUiSpecimens: Specimen[] = [
  // ── Chrome ───────────────────────────────────────────────────────────────────────────────────
  {
    id: 'cu-site-header',
    name: 'SiteHeader',
    pkg: 'common-ui',
    domains: ['chrome'],
    kind: 'interactive',
    load: ex,
    exportName: 'SiteHeaderExample',
  },
  {
    id: 'cu-theme-switcher',
    name: 'ThemeSwitcher',
    pkg: 'common-ui',
    domains: ['chrome'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-common-ui/ThemeSwitcher'),
  },
  {
    id: 'cu-language-switcher',
    name: 'LanguageSwitcher',
    pkg: 'common-ui',
    domains: ['chrome'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-common-ui/LanguageSwitcher'),
  },
  {
    id: 'cu-settings-menu',
    name: 'SettingsMenu',
    pkg: 'common-ui',
    domains: ['chrome'],
    kind: 'interactive',
    defaultProps: { i18nEnabled: true },
    load: () => import('@TheY2T/tmr-common-ui/SettingsMenu'),
  },
  {
    id: 'cu-info-view',
    name: 'InfoView',
    pkg: 'common-ui',
    domains: ['chrome'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-common-ui/InfoView'),
  },
  {
    id: 'cu-flag-banner',
    name: 'FlagBanner',
    pkg: 'common-ui',
    domains: ['chrome'],
    kind: 'presentational',
    defaultProps: { initial: true },
    load: () => import('@TheY2T/tmr-common-ui/FlagBanner'),
  },
  {
    id: 'cu-ambient-background',
    name: 'AmbientBackground',
    pkg: 'common-ui',
    domains: ['chrome'],
    kind: 'pixi',
    defaultProps: { className: 'h-64 w-full rounded-md' },
    load: () => import('@TheY2T/tmr-common-ui/AmbientBackground'),
  },
  {
    id: 'cu-dashboard-background',
    name: 'DashboardBackground',
    pkg: 'common-ui',
    domains: ['dashboard'],
    kind: 'pixi',
    defaultProps: { className: 'h-64 w-full rounded-md' },
    load: () => import('@TheY2T/tmr-common-ui/DashboardBackground'),
  },
  {
    id: 'cu-health-card',
    name: 'HealthCard',
    pkg: 'common-ui',
    domains: ['chrome'],
    kind: 'interactive',
    notes: 'Reads the data-access port (mock reports a healthy API).',
    load: () => import('@TheY2T/tmr-common-ui/HealthCard'),
  },

  // ── Home / dashboards / widgets ────────────────────────────────────────────────────────────
  {
    id: 'cu-home-page',
    name: 'HomePage',
    pkg: 'common-ui',
    domains: ['catalogue'],
    kind: 'interactive',
    defaultProps: {
      catalogueHref: '/catalogue',
      toolsHref: '/tools',
      collectionsHref: '/collections',
      upgradeHref: '/upgrade',
      showTools: true,
      showCollections: true,
      showUpgrade: false,
      showMonetization: false,
    },
    load: () => import('@TheY2T/tmr-common-ui/HomePage'),
  },
  {
    id: 'cu-progress-dashboard',
    name: 'ProgressDashboard',
    pkg: 'common-ui',
    domains: ['dashboard'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-common-ui/ProgressDashboard'),
  },
  {
    id: 'cu-spaces-builder',
    name: 'SpacesBuilder',
    pkg: 'common-ui',
    domains: ['dashboard'],
    kind: 'interactive',
    notes: 'Drag-and-drop practice-space builder (react-grid-layout + dnd-kit).',
    load: () => import('@TheY2T/tmr-common-ui/DashboardSpaces/SpacesBuilder'),
  },
  {
    id: 'cu-achievements-widget',
    name: 'AchievementsWidget',
    pkg: 'common-ui',
    domains: ['dashboard'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-common-ui/DashboardSpaces/AchievementsWidget'),
  },
  {
    id: 'cu-progress-widget',
    name: 'ProgressWidget',
    pkg: 'common-ui',
    domains: ['dashboard'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-common-ui/DashboardSpaces/ProgressWidget'),
  },
  {
    id: 'cu-note-widget',
    name: 'NoteWidget',
    pkg: 'common-ui',
    domains: ['dashboard'],
    kind: 'interactive',
    defaultProps: { text: 'Practice the C major scale, hands together, 60 BPM.' },
    load: () => import('@TheY2T/tmr-common-ui/DashboardSpaces/NoteWidget'),
  },
  {
    id: 'cu-collections-widget',
    name: 'CollectionsWidget',
    pkg: 'common-ui',
    domains: ['dashboard', 'collections'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-common-ui/DashboardSpaces/CollectionsWidget'),
  },

  // ── Account / auth / billing ──────────────────────────────────────────────────────────────
  {
    id: 'cu-sign-in-form',
    name: 'SignInForm',
    pkg: 'common-ui',
    domains: ['account'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-common-ui/SignInForm'),
  },
  {
    id: 'cu-sign-out-button',
    name: 'SignOutButton',
    pkg: 'common-ui',
    domains: ['account'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-common-ui/SignOutButton'),
  },
  {
    id: 'cu-forgot-password-form',
    name: 'ForgotPasswordForm',
    pkg: 'common-ui',
    domains: ['account'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-common-ui/ForgotPasswordForm'),
  },
  {
    id: 'cu-my-favorites',
    name: 'MyFavorites',
    pkg: 'common-ui',
    domains: ['account'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-common-ui/MyFavorites'),
  },
  {
    id: 'cu-favorite-button',
    name: 'FavoriteButton',
    pkg: 'common-ui',
    domains: ['account'],
    kind: 'interactive',
    defaultProps: { slug: 'example-score' },
    load: () => import('@TheY2T/tmr-common-ui/FavoriteButton'),
  },
  {
    id: 'cu-complete-button',
    name: 'CompleteButton',
    pkg: 'common-ui',
    domains: ['account'],
    kind: 'interactive',
    defaultProps: { slug: 'example-score' },
    load: () => import('@TheY2T/tmr-common-ui/CompleteButton'),
  },
  {
    id: 'cu-upgrade-panel',
    name: 'UpgradePanel',
    pkg: 'common-ui',
    domains: ['account'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-common-ui/UpgradePanel'),
  },
  {
    id: 'cu-mock-checkout',
    name: 'MockCheckout',
    pkg: 'common-ui',
    domains: ['account'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-common-ui/MockCheckout'),
  },
  {
    id: 'cu-support-panel',
    name: 'SupportPanel',
    pkg: 'common-ui',
    domains: ['account'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-common-ui/SupportPanel'),
  },

  // ── Feedback / NPS ─────────────────────────────────────────────────────────────────────────
  {
    id: 'cu-feedback-form',
    name: 'FeedbackForm',
    pkg: 'common-ui',
    domains: ['feedback'],
    kind: 'interactive',
    defaultProps: { bugsEnabled: true },
    load: () => import('@TheY2T/tmr-common-ui/FeedbackForm'),
  },
  {
    id: 'cu-feedback-board',
    name: 'FeedbackBoard',
    pkg: 'common-ui',
    domains: ['feedback'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-common-ui/FeedbackBoard'),
  },
  {
    id: 'cu-feedback-launcher',
    name: 'FeedbackLauncher',
    pkg: 'common-ui',
    domains: ['feedback'],
    kind: 'interactive',
    defaultProps: { bugsEnabled: true },
    load: () => import('@TheY2T/tmr-common-ui/FeedbackLauncher'),
  },
  {
    id: 'cu-nps-prompt',
    name: 'NpsPrompt',
    pkg: 'common-ui',
    domains: ['feedback'],
    kind: 'interactive',
    defaultProps: { signedIn: true, source: '/sandbox' },
    load: () => import('@TheY2T/tmr-common-ui/NpsPrompt'),
  },

  // ── Admin CMS ────────────────────────────────────────────────────────────────────────────────
  {
    id: 'cu-admin-content',
    name: 'AdminContentManager',
    pkg: 'common-ui',
    domains: ['admin'],
    kind: 'interactive',
    notes: 'CRUD via the API; renders loading/empty offline.',
    load: () => import('@TheY2T/tmr-common-ui/AdminContentManager'),
  },
  {
    id: 'cu-admin-collections',
    name: 'AdminCollectionManager',
    pkg: 'common-ui',
    domains: ['admin'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-common-ui/AdminCollectionManager'),
  },
  {
    id: 'cu-admin-flags',
    name: 'AdminFlagManager',
    pkg: 'common-ui',
    domains: ['admin'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-common-ui/AdminFlagManager'),
  },
  {
    id: 'cu-admin-locale',
    name: 'AdminLocaleManager',
    pkg: 'common-ui',
    domains: ['admin'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-common-ui/AdminLocaleManager'),
  },
  {
    id: 'cu-admin-faq',
    name: 'AdminFaqManager',
    pkg: 'common-ui',
    domains: ['admin'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-common-ui/AdminFaqManager'),
  },
  {
    id: 'cu-classrooms',
    name: 'ClassroomsManager',
    pkg: 'common-ui',
    domains: ['admin'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-common-ui/ClassroomsManager'),
  },
];
