import type { Specimen } from './types';

// The music/learning experiences: interactive tool islands, score surfaces, catalogue/collections,
// drills, and the SVG music organisms. Each loads its own package subpath (default export). Most tools
// are self-contained; the built-in locale control is applied by the stage. Pixi-backed tools are marked
// `kind: 'pixi'` (WebGL, E2E-tested). Example wrappers cover components that need sample data props.
const ex = () => import('@/examples/musickit-examples');

export const musickitSpecimens: Specimen[] = [
  // ── Keyboard / fretboard / chords ────────────────────────────────────────────────────────────
  {
    id: 'mk-piano-keyboard',
    name: 'PianoKeyboard',
    pkg: 'musickit-ui',
    domains: ['keyboard'],
    kind: 'pixi',
    inspector: 'soundfont',
    load: () => import('@TheY2T/tmr-musickit-ui/PianoKeyboard'),
  },
  {
    id: 'mk-guitar-fretboard',
    name: 'GuitarFretboard',
    pkg: 'musickit-ui',
    domains: ['fretboard'],
    kind: 'pixi',
    inspector: 'soundfont',
    load: () => import('@TheY2T/tmr-musickit-ui/GuitarFretboard'),
  },
  {
    id: 'mk-chord-diagrams',
    name: 'ChordDiagrams',
    pkg: 'musickit-ui',
    domains: ['chords'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/ChordDiagrams'),
  },
  {
    id: 'mk-chord-dictionary',
    name: 'ChordDictionary',
    pkg: 'musickit-ui',
    domains: ['chords'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/ChordDictionary'),
  },
  {
    id: 'mk-caged-explorer',
    name: 'CagedExplorer',
    pkg: 'musickit-ui',
    domains: ['fretboard', 'chords'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/CagedExplorer'),
  },
  {
    id: 'mk-scale-boxes',
    name: 'ScaleBoxes',
    pkg: 'musickit-ui',
    domains: ['fretboard'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/ScaleBoxes'),
  },
  {
    id: 'mk-voicing-library',
    name: 'VoicingLibrary',
    pkg: 'musickit-ui',
    domains: ['chords'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/VoicingLibrary'),
  },
  {
    id: 'mk-scale-heatmap',
    name: 'ScaleHeatmap',
    pkg: 'musickit-ui',
    domains: ['fretboard'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/ScaleHeatmap'),
  },
  {
    id: 'mk-lick-library',
    name: 'LickLibrary',
    pkg: 'musickit-ui',
    domains: ['fretboard'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/LickLibrary'),
  },

  // ── Theory / harmony ─────────────────────────────────────────────────────────────────────────
  {
    id: 'mk-circle-of-fifths',
    name: 'CircleOfFifths',
    pkg: 'musickit-ui',
    domains: ['theory'],
    kind: 'pixi',
    inspector: 'theory',
    load: () => import('@TheY2T/tmr-musickit-ui/CircleOfFifths'),
  },
  {
    id: 'mk-scale-explorer',
    name: 'ScaleExplorer',
    pkg: 'musickit-ui',
    domains: ['theory'],
    kind: 'interactive',
    inspector: 'theory',
    load: () => import('@TheY2T/tmr-musickit-ui/ScaleExplorer'),
  },
  {
    id: 'mk-chord-board',
    name: 'ChordBoard',
    pkg: 'musickit-ui',
    domains: ['chords', 'theory'],
    kind: 'pixi',
    load: () => import('@TheY2T/tmr-musickit-ui/ChordBoard'),
  },
  {
    id: 'mk-chord-builder',
    name: 'ChordBuilder',
    pkg: 'musickit-ui',
    domains: ['chords', 'theory'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/ChordBuilder'),
  },
  {
    id: 'mk-chord-analyzer',
    name: 'ChordAnalyzer',
    pkg: 'musickit-ui',
    domains: ['chords', 'theory'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/ChordAnalyzer'),
  },
  {
    id: 'mk-chord-identifier',
    name: 'ChordIdentifier',
    pkg: 'musickit-ui',
    domains: ['chords', 'theory'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/ChordIdentifier'),
  },
  {
    id: 'mk-mode-explorer',
    name: 'ModeExplorer',
    pkg: 'musickit-ui',
    domains: ['theory'],
    kind: 'interactive',
    inspector: 'theory',
    load: () => import('@TheY2T/tmr-musickit-ui/ModeExplorer'),
  },
  {
    id: 'mk-interval-explorer',
    name: 'IntervalExplorer',
    pkg: 'musickit-ui',
    domains: ['theory'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/IntervalExplorer'),
  },
  {
    id: 'mk-intervals',
    name: 'Intervals',
    pkg: 'musickit-ui',
    domains: ['theory'],
    kind: 'pixi',
    load: () => import('@TheY2T/tmr-musickit-ui/Intervals'),
  },
  {
    id: 'mk-transposer',
    name: 'Transposer',
    pkg: 'musickit-ui',
    domains: ['theory'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/Transposer'),
  },
  {
    id: 'mk-improvise-guide',
    name: 'ImproviseGuide',
    pkg: 'musickit-ui',
    domains: ['theory'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/ImproviseGuide'),
  },
  {
    id: 'mk-progression-builder',
    name: 'ProgressionBuilder',
    pkg: 'musickit-ui',
    domains: ['theory'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/ProgressionBuilder'),
  },
  {
    id: 'mk-progression-generator',
    name: 'ProgressionGenerator',
    pkg: 'musickit-ui',
    domains: ['theory'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/ProgressionGenerator'),
  },
  {
    id: 'mk-progression-player',
    name: 'ProgressionPlayer',
    pkg: 'musickit-ui',
    domains: ['theory'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/ProgressionPlayer'),
  },
  {
    id: 'mk-voice-leading-viewer',
    name: 'VoiceLeadingViewer',
    pkg: 'musickit-ui',
    domains: ['theory'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/VoiceLeadingViewer'),
  },
  {
    id: 'mk-solfege',
    name: 'Solfege',
    pkg: 'musickit-ui',
    domains: ['theory', 'ear'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/Solfege'),
  },
  {
    id: 'mk-bass-line-generator',
    name: 'BassLineGenerator',
    pkg: 'musickit-ui',
    domains: ['theory', 'rhythm'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/BassLineGenerator'),
  },

  // ── Ear training / quizzes / reading ──────────────────────────────────────────────────────────
  {
    id: 'mk-ear-trainer',
    name: 'EarTrainer',
    pkg: 'musickit-ui',
    domains: ['ear'],
    kind: 'interactive',
    inspector: 'audio',
    load: () => import('@TheY2T/tmr-musickit-ui/EarTrainer'),
  },
  {
    id: 'mk-progression-ear',
    name: 'ProgressionEar',
    pkg: 'musickit-ui',
    domains: ['ear'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/ProgressionEar'),
  },
  {
    id: 'mk-chord-quality-ear',
    name: 'ChordQualityEar',
    pkg: 'musickit-ui',
    domains: ['ear'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/ChordQualityEar'),
  },
  {
    id: 'mk-melodic-dictation',
    name: 'MelodicDictation',
    pkg: 'musickit-ui',
    domains: ['ear'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/MelodicDictation'),
  },
  {
    id: 'mk-rhythm-dictation',
    name: 'RhythmDictation',
    pkg: 'musickit-ui',
    domains: ['ear', 'rhythm'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/RhythmDictation'),
  },
  {
    id: 'mk-fretboard-note-quiz',
    name: 'FretboardNoteQuiz',
    pkg: 'musickit-ui',
    domains: ['fretboard', 'ear'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/FretboardNoteQuiz'),
  },
  {
    id: 'mk-fretboard-game',
    name: 'FretboardGame',
    pkg: 'musickit-ui',
    domains: ['fretboard'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/FretboardGame'),
  },
  {
    id: 'mk-staff-game',
    name: 'StaffGame',
    pkg: 'musickit-ui',
    domains: ['reading'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/StaffGame'),
  },
  {
    id: 'mk-staff-reader',
    name: 'StaffReader',
    pkg: 'musickit-ui',
    domains: ['reading'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/StaffReader'),
  },
  {
    id: 'mk-staff-note-prompt',
    name: 'StaffNotePrompt',
    pkg: 'musickit-ui',
    domains: ['reading'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/StaffNotePrompt'),
  },
  {
    id: 'mk-key-signature-game',
    name: 'KeySignatureGame',
    pkg: 'musickit-ui',
    domains: ['reading', 'theory'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/KeySignatureGame'),
  },
  {
    id: 'mk-key-signature-quiz',
    name: 'KeySignatureQuiz',
    pkg: 'musickit-ui',
    domains: ['reading', 'theory'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/KeySignatureQuiz'),
  },
  {
    id: 'mk-interval-construction-quiz',
    name: 'IntervalConstructionQuiz',
    pkg: 'musickit-ui',
    domains: ['theory', 'ear'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/IntervalConstructionQuiz'),
  },
  {
    id: 'mk-sight-reading-trainer',
    name: 'SightReadingTrainer',
    pkg: 'musickit-ui',
    domains: ['reading'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/SightReadingTrainer'),
  },

  // ── Rhythm / time ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'mk-metronome',
    name: 'Metronome',
    pkg: 'musickit-ui',
    domains: ['rhythm'],
    kind: 'interactive',
    inspector: 'audio',
    load: () => import('@TheY2T/tmr-musickit-ui/Metronome'),
  },
  {
    id: 'mk-beat-sequencer',
    name: 'BeatSequencer',
    pkg: 'musickit-ui',
    domains: ['rhythm'],
    kind: 'interactive',
    inspector: 'audio',
    load: () => import('@TheY2T/tmr-musickit-ui/BeatSequencer'),
  },
  {
    id: 'mk-rhythm',
    name: 'Rhythm',
    pkg: 'musickit-ui',
    domains: ['rhythm'],
    kind: 'pixi',
    load: () => import('@TheY2T/tmr-musickit-ui/Rhythm'),
  },
  {
    id: 'mk-rhythm-tap-game',
    name: 'RhythmTapGame',
    pkg: 'musickit-ui',
    domains: ['rhythm'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/RhythmTapGame'),
  },
  {
    id: 'mk-rhythm-trainer',
    name: 'RhythmTrainer',
    pkg: 'musickit-ui',
    domains: ['rhythm'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/RhythmTrainer'),
  },
  {
    id: 'mk-strumming-trainer',
    name: 'StrummingTrainer',
    pkg: 'musickit-ui',
    domains: ['rhythm', 'fretboard'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/StrummingTrainer'),
  },
  {
    id: 'mk-strum-pattern',
    name: 'StrumPattern',
    pkg: 'musickit-ui',
    domains: ['rhythm'],
    kind: 'pixi',
    load: () => import('@TheY2T/tmr-musickit-ui/StrumPattern'),
  },
  {
    id: 'mk-speed-trainer',
    name: 'SpeedTrainer',
    pkg: 'musickit-ui',
    domains: ['rhythm'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/SpeedTrainer'),
  },
  {
    id: 'mk-groove-library',
    name: 'GrooveLibrary',
    pkg: 'musickit-ui',
    domains: ['rhythm'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/GrooveLibrary'),
  },
  {
    id: 'mk-fingering',
    name: 'Fingering',
    pkg: 'musickit-ui',
    domains: ['fretboard'],
    kind: 'pixi',
    load: () => import('@TheY2T/tmr-musickit-ui/Fingering'),
  },
  {
    id: 'mk-fingerpicking-trainer',
    name: 'FingerpickingTrainer',
    pkg: 'musickit-ui',
    domains: ['fretboard', 'rhythm'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/FingerpickingTrainer'),
  },

  // ── Tuner / audio reference ──────────────────────────────────────────────────────────────────
  {
    id: 'mk-tuning-reference',
    name: 'TuningReference',
    pkg: 'musickit-ui',
    domains: ['fretboard'],
    kind: 'pixi',
    inspector: 'audio',
    load: () => import('@TheY2T/tmr-musickit-ui/TuningReference'),
  },
  {
    id: 'mk-audio-visualizer',
    name: 'AudioVisualizer',
    pkg: 'musickit-ui',
    domains: ['engines'],
    kind: 'pixi',
    inspector: 'audio',
    load: () => import('@TheY2T/tmr-musickit-ui/AudioVisualizer'),
  },

  // ── Play / practice / players (scores) ───────────────────────────────────────────────────────
  {
    id: 'mk-practice-room',
    name: 'PracticeRoom',
    pkg: 'musickit-ui',
    domains: ['scores'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/PracticeRoom'),
  },
  {
    id: 'mk-practice-planner',
    name: 'PracticePlanner',
    pkg: 'musickit-ui',
    domains: ['scores'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/PracticePlanner'),
  },
  {
    id: 'mk-practice-player',
    name: 'PracticePlayer',
    pkg: 'musickit-ui',
    domains: ['scores'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/PracticePlayer'),
  },
  {
    id: 'mk-song-player',
    name: 'SongPlayer',
    pkg: 'musickit-ui',
    domains: ['scores'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/SongPlayer'),
  },
  {
    id: 'mk-notation-player',
    name: 'NotationPlayer',
    pkg: 'musickit-ui',
    domains: ['scores'],
    kind: 'interactive',
    inspector: 'score',
    load: () => import('@TheY2T/tmr-musickit-ui/NotationPlayer'),
  },
  {
    id: 'mk-arpeggio-player',
    name: 'ArpeggioPlayer',
    pkg: 'musickit-ui',
    domains: ['scores'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/ArpeggioPlayer'),
  },
  {
    id: 'mk-backing-track',
    name: 'BackingTrack',
    pkg: 'musickit-ui',
    domains: ['scores', 'rhythm'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/BackingTrack'),
  },
  {
    id: 'mk-animated-cover-art',
    name: 'AnimatedCoverArt',
    pkg: 'musickit-ui',
    domains: ['catalogue'],
    kind: 'pixi',
    load: () => import('@TheY2T/tmr-musickit-ui/AnimatedCoverArt'),
  },
  {
    id: 'mk-score-player',
    name: 'ScorePlayer',
    pkg: 'musickit-ui',
    domains: ['scores'],
    kind: 'interactive',
    inspector: 'score',
    load: ex,
    exportName: 'ScorePlayerExample',
  },
  {
    id: 'mk-alphatex-score',
    name: 'AlphaTexScore',
    pkg: 'musickit-ui',
    domains: ['scores'],
    kind: 'interactive',
    inspector: 'score',
    load: ex,
    exportName: 'AlphaTexScoreExample',
  },

  // ── Instrument helpers ───────────────────────────────────────────────────────────────────────
  {
    id: 'mk-instrument-picker',
    name: 'InstrumentPicker',
    pkg: 'musickit-ui',
    domains: ['keyboard'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/InstrumentPicker'),
  },
  {
    id: 'mk-instrument-loading',
    name: 'InstrumentLoading',
    pkg: 'musickit-ui',
    domains: ['keyboard'],
    kind: 'presentational',
    load: () => import('@TheY2T/tmr-musickit-ui/InstrumentLoading'),
  },
  {
    id: 'mk-level-toggle',
    name: 'LevelToggle',
    pkg: 'musickit-ui',
    domains: ['theory'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/LevelToggle'),
  },

  // ── Drills ───────────────────────────────────────────────────────────────────────────────────
  {
    id: 'mk-drill-session',
    name: 'DrillSession',
    pkg: 'musickit-ui',
    domains: ['drills'],
    kind: 'interactive',
    notes: 'Records attempts to the API; runs in loading/empty state offline.',
    load: () => import('@TheY2T/tmr-musickit-ui/DrillSession'),
  },
  {
    id: 'mk-drills-hub',
    name: 'DrillsHub',
    pkg: 'musickit-ui',
    domains: ['drills'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/DrillsHub'),
  },
  {
    id: 'mk-drill-feedback',
    name: 'DrillFeedback',
    pkg: 'musickit-ui',
    domains: ['drills'],
    kind: 'pixi',
    load: () => import('@TheY2T/tmr-musickit-ui/DrillFeedback'),
  },

  // ── Catalogue / collections / content (data-access port) ─────────────────────────────────────
  {
    id: 'mk-catalogue-browser',
    name: 'CatalogueBrowser',
    pkg: 'musickit-ui',
    domains: ['catalogue'],
    kind: 'interactive',
    notes: 'Reads the data-access port (mock returns empty results).',
    load: () => import('@TheY2T/tmr-musickit-ui/CatalogueBrowser'),
  },
  {
    id: 'mk-catalogue-hub',
    name: 'CatalogueHub',
    pkg: 'musickit-ui',
    domains: ['catalogue'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/CatalogueHub'),
  },
  {
    id: 'mk-collections-browser',
    name: 'CollectionsBrowser',
    pkg: 'musickit-ui',
    domains: ['collections'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/CollectionsBrowser'),
  },
  {
    id: 'mk-collections-hub',
    name: 'CollectionsHub',
    pkg: 'musickit-ui',
    domains: ['collections'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/CollectionsHub'),
  },
  {
    id: 'mk-collection-detail',
    name: 'CollectionDetail',
    pkg: 'musickit-ui',
    domains: ['collections'],
    kind: 'interactive',
    defaultProps: { slug: 'example-collection' },
    load: () => import('@TheY2T/tmr-musickit-ui/CollectionDetail'),
  },
  {
    id: 'mk-content-detail',
    name: 'ContentDetail',
    pkg: 'musickit-ui',
    domains: ['catalogue', 'content'],
    kind: 'interactive',
    defaultProps: { slug: 'example-score' },
    load: () => import('@TheY2T/tmr-musickit-ui/ContentDetail'),
  },
  {
    id: 'mk-tools-browser',
    name: 'ToolsBrowser',
    pkg: 'musickit-ui',
    domains: ['catalogue'],
    kind: 'interactive',
    load: () => import('@TheY2T/tmr-musickit-ui/ToolsBrowser'),
  },
  {
    id: 'mk-content-body',
    name: 'ContentBody',
    pkg: 'musickit-ui',
    domains: ['content'],
    kind: 'presentational',
    load: ex,
    exportName: 'ContentBodyExample',
  },

  // ── Organisms (presentational SVG) ───────────────────────────────────────────────────────────
  {
    id: 'mk-chord-diagram',
    name: 'ChordDiagram',
    pkg: 'musickit-ui',
    domains: ['organisms', 'chords'],
    kind: 'organism',
    load: ex,
    exportName: 'ChordDiagramExample',
  },
  {
    id: 'mk-keyboard-chord-diagram',
    name: 'KeyboardChordDiagram',
    pkg: 'musickit-ui',
    domains: ['organisms', 'chords'],
    kind: 'organism',
    load: ex,
    exportName: 'KeyboardChordDiagramExample',
  },
  {
    id: 'mk-staff-sequence',
    name: 'StaffSequence',
    pkg: 'musickit-ui',
    domains: ['organisms', 'reading'],
    kind: 'organism',
    load: ex,
    exportName: 'StaffSequenceExample',
  },
];
