import type { Specimen } from './types';

// Design-system foundation: atoms (shadcn primitives) + molecules from @TheY2T/tmr-ui. Strictly
// presentational, so most load straight from the barrel with playground controls; compound components
// (trees of sub-parts, controlled state, render props) load from the pre-composed examples module.
const barrel = () => import('@TheY2T/tmr-ui');
const examples = () => import('@/examples/ui-examples');

const BUTTON_VARIANTS = ['default', 'secondary', 'outline', 'ghost', 'destructive', 'link'];
const BADGE_VARIANTS = [
  'default',
  'secondary',
  'outline',
  'destructive',
  'success',
  'warning',
  'info',
];
const ICON_NAMES = [
  'music',
  'play',
  'pause',
  'heart',
  'star',
  'lock',
  'check',
  'search',
  'settings',
  'guitar',
];

export const uiSpecimens: Specimen[] = [
  // ── Atoms ──────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'ui-button',
    name: 'Button',
    pkg: 'ui',
    domains: ['atoms'],
    kind: 'presentational',
    load: barrel,
    exportName: 'Button',
    controls: [
      { name: 'children', type: 'text', label: 'Label', default: 'Play scale' },
      {
        name: 'variant',
        type: 'enum',
        default: 'default',
        options: BUTTON_VARIANTS.map((v) => ({ value: v })),
      },
      {
        name: 'size',
        type: 'enum',
        default: 'default',
        options: ['default', 'sm', 'lg'].map((v) => ({ value: v })),
      },
      { name: 'disabled', type: 'boolean', default: false },
    ],
  },
  {
    id: 'ui-badge',
    name: 'Badge',
    pkg: 'ui',
    domains: ['atoms'],
    kind: 'presentational',
    load: barrel,
    exportName: 'Badge',
    controls: [
      { name: 'children', type: 'text', label: 'Label', default: 'Beginner' },
      {
        name: 'variant',
        type: 'enum',
        default: 'default',
        options: BADGE_VARIANTS.map((v) => ({ value: v })),
      },
    ],
  },
  {
    id: 'ui-chip',
    name: 'Chip',
    pkg: 'ui',
    domains: ['atoms'],
    kind: 'presentational',
    load: barrel,
    exportName: 'Chip',
    controls: [
      { name: 'children', type: 'text', label: 'Label', default: 'Romantic' },
      {
        name: 'variant',
        type: 'enum',
        default: 'outline',
        options: [{ value: 'outline' }, { value: 'muted' }],
      },
      { name: 'active', type: 'boolean', default: false },
    ],
  },
  {
    id: 'ui-icon',
    name: 'Icon',
    pkg: 'ui',
    domains: ['atoms'],
    kind: 'presentational',
    load: barrel,
    exportName: 'Icon',
    controls: [
      {
        name: 'name',
        type: 'enum',
        default: 'music',
        options: ICON_NAMES.map((v) => ({ value: v })),
      },
      { name: 'className', type: 'text', label: 'Class', default: 'size-8' },
    ],
  },
  {
    id: 'ui-input',
    name: 'Input',
    pkg: 'ui',
    domains: ['atoms'],
    kind: 'presentational',
    load: barrel,
    exportName: 'Input',
    controls: [
      { name: 'placeholder', type: 'text', default: 'Search scores…' },
      { name: 'disabled', type: 'boolean', default: false },
    ],
  },
  {
    id: 'ui-textarea',
    name: 'Textarea',
    pkg: 'ui',
    domains: ['atoms'],
    kind: 'presentational',
    load: barrel,
    exportName: 'Textarea',
    controls: [{ name: 'placeholder', type: 'text', default: 'Practice notes…' }],
  },
  {
    id: 'ui-label',
    name: 'Label',
    pkg: 'ui',
    domains: ['atoms'],
    kind: 'presentational',
    load: barrel,
    exportName: 'Label',
    controls: [{ name: 'children', type: 'text', label: 'Text', default: 'Tempo (BPM)' }],
  },
  {
    id: 'ui-checkbox',
    name: 'Checkbox',
    pkg: 'ui',
    domains: ['atoms'],
    kind: 'presentational',
    load: barrel,
    exportName: 'Checkbox',
    controls: [
      { name: 'checked', type: 'boolean', default: true },
      { name: 'disabled', type: 'boolean', default: false },
    ],
  },
  {
    id: 'ui-slider',
    name: 'Slider',
    pkg: 'ui',
    domains: ['atoms'],
    kind: 'presentational',
    load: barrel,
    exportName: 'Slider',
    defaultProps: { defaultValue: 60, min: 40, max: 208 },
  },
  {
    id: 'ui-progress',
    name: 'Progress',
    pkg: 'ui',
    domains: ['atoms'],
    kind: 'presentational',
    load: barrel,
    exportName: 'Progress',
    controls: [{ name: 'value', type: 'number', default: 65, min: 0, max: 100, step: 1 }],
    defaultProps: { className: 'w-64' },
  },
  {
    id: 'ui-separator',
    name: 'Separator',
    pkg: 'ui',
    domains: ['atoms'],
    kind: 'presentational',
    load: barrel,
    exportName: 'Separator',
    controls: [
      {
        name: 'orientation',
        type: 'enum',
        default: 'horizontal',
        options: [{ value: 'horizontal' }, { value: 'vertical' }],
      },
    ],
    defaultProps: { className: 'w-64' },
  },
  {
    id: 'ui-skeleton',
    name: 'Skeleton',
    pkg: 'ui',
    domains: ['atoms'],
    kind: 'presentational',
    load: barrel,
    exportName: 'Skeleton',
    defaultProps: { className: 'h-8 w-64' },
  },
  {
    id: 'ui-avatar',
    name: 'Avatar',
    pkg: 'ui',
    domains: ['atoms'],
    kind: 'presentational',
    load: examples,
    exportName: 'AvatarExample',
  },
  {
    id: 'ui-accordion',
    name: 'Accordion',
    pkg: 'ui',
    domains: ['atoms'],
    kind: 'interactive',
    load: examples,
    exportName: 'AccordionExample',
  },
  {
    id: 'ui-breadcrumb',
    name: 'Breadcrumb',
    pkg: 'ui',
    domains: ['atoms'],
    kind: 'presentational',
    load: examples,
    exportName: 'BreadcrumbExample',
  },
  {
    id: 'ui-card',
    name: 'Card',
    pkg: 'ui',
    domains: ['atoms'],
    kind: 'presentational',
    load: examples,
    exportName: 'CardExample',
  },
  {
    id: 'ui-dialog',
    name: 'Dialog',
    pkg: 'ui',
    domains: ['atoms'],
    kind: 'interactive',
    load: examples,
    exportName: 'DialogExample',
  },
  {
    id: 'ui-sheet',
    name: 'Sheet',
    pkg: 'ui',
    domains: ['atoms'],
    kind: 'interactive',
    load: examples,
    exportName: 'SheetExample',
  },
  {
    id: 'ui-dropdown-menu',
    name: 'DropdownMenu',
    pkg: 'ui',
    domains: ['atoms'],
    kind: 'interactive',
    load: examples,
    exportName: 'DropdownMenuExample',
  },
  {
    id: 'ui-tooltip',
    name: 'Tooltip',
    pkg: 'ui',
    domains: ['atoms'],
    kind: 'interactive',
    load: examples,
    exportName: 'TooltipExample',
  },
  {
    id: 'ui-tabs',
    name: 'Tabs',
    pkg: 'ui',
    domains: ['atoms'],
    kind: 'interactive',
    load: examples,
    exportName: 'TabsExample',
  },
  {
    id: 'ui-table',
    name: 'Table',
    pkg: 'ui',
    domains: ['atoms'],
    kind: 'presentational',
    load: examples,
    exportName: 'TableExample',
  },
  {
    id: 'ui-toaster',
    name: 'Toaster',
    pkg: 'ui',
    domains: ['atoms'],
    kind: 'interactive',
    load: examples,
    exportName: 'ToasterExample',
  },

  // ── Molecules ──────────────────────────────────────────────────────────────────────────────────
  {
    id: 'ui-stat-card',
    name: 'StatCard',
    pkg: 'ui',
    domains: ['molecules'],
    kind: 'presentational',
    load: barrel,
    exportName: 'StatCard',
    controls: [
      { name: 'label', type: 'text', default: 'Day streak' },
      { name: 'value', type: 'text', default: '12' },
      { name: 'hint', type: 'text', default: 'Keep it going!' },
    ],
  },
  {
    id: 'ui-stat-tile',
    name: 'StatTile',
    pkg: 'ui',
    domains: ['molecules'],
    kind: 'presentational',
    load: barrel,
    exportName: 'StatTile',
    controls: [
      {
        name: 'iconName',
        type: 'enum',
        default: 'flame',
        options: ['flame', 'star', 'clock', 'chart'].map((v) => ({ value: v })),
      },
      { name: 'label', type: 'text', default: 'XP earned' },
      { name: 'value', type: 'text', default: '1,240' },
      { name: 'hint', type: 'text', default: 'this month' },
    ],
  },
  {
    id: 'ui-star-rating',
    name: 'StarRating',
    pkg: 'ui',
    domains: ['molecules'],
    kind: 'presentational',
    load: barrel,
    exportName: 'StarRating',
    controls: [
      { name: 'value', type: 'number', default: 4, min: 0, max: 5, step: 1 },
      { name: 'count', type: 'number', default: 5, min: 3, max: 10, step: 1 },
      { name: 'readOnly', type: 'boolean', default: true },
      { name: 'size', type: 'enum', default: 'md', options: [{ value: 'sm' }, { value: 'md' }] },
    ],
  },
  {
    id: 'ui-empty-state',
    name: 'EmptyState',
    pkg: 'ui',
    domains: ['molecules'],
    kind: 'presentational',
    load: barrel,
    exportName: 'EmptyState',
    controls: [
      { name: 'title', type: 'text', default: 'No results' },
      { name: 'description', type: 'text', default: 'Try adjusting your filters.' },
    ],
  },
  {
    id: 'ui-search-field',
    name: 'SearchField',
    pkg: 'ui',
    domains: ['molecules'],
    kind: 'presentational',
    load: barrel,
    exportName: 'SearchField',
    controls: [{ name: 'placeholder', type: 'text', default: 'Search the catalogue…' }],
    defaultProps: { className: 'w-80' },
  },
  {
    id: 'ui-page-header',
    name: 'PageHeader',
    pkg: 'ui',
    domains: ['molecules'],
    kind: 'presentational',
    load: barrel,
    exportName: 'PageHeader',
    controls: [
      { name: 'title', type: 'text', default: 'Chord dictionary' },
      { name: 'subtitle', type: 'text', default: 'Every chord, every voicing.' },
    ],
  },
  {
    id: 'ui-hero',
    name: 'Hero',
    pkg: 'ui',
    domains: ['molecules'],
    kind: 'presentational',
    load: barrel,
    exportName: 'Hero',
    controls: [
      { name: 'eyebrow', type: 'text', default: 'The Music Repository' },
      { name: 'title', type: 'text', default: 'Learn music, deeply' },
      { name: 'subtitle', type: 'text', default: 'A catalogue of scores, tools, and lessons.' },
    ],
  },
  {
    id: 'ui-cover-art',
    name: 'CoverArt',
    pkg: 'ui',
    domains: ['molecules'],
    kind: 'presentational',
    load: barrel,
    exportName: 'CoverArt',
    controls: [
      { name: 'title', type: 'text', default: 'Nocturne' },
      { name: 'subtitle', type: 'text', default: 'Chopin' },
      { name: 'seed', type: 'text', default: 'nocturne' },
      {
        name: 'motif',
        type: 'enum',
        default: 'record',
        options: ['record', 'staff', 'keys', 'strings'].map((v) => ({ value: v })),
      },
      { name: 'showLabel', type: 'boolean', default: true },
    ],
    defaultProps: { className: 'size-48' },
  },
  {
    id: 'ui-media-card',
    name: 'MediaCard',
    pkg: 'ui',
    domains: ['molecules'],
    kind: 'presentational',
    load: barrel,
    exportName: 'MediaCard',
    controls: [
      { name: 'title', type: 'text', default: 'Prelude in C' },
      { name: 'summary', type: 'text', default: 'J.S. Bach · BWV 846' },
      { name: 'typeLabel', type: 'text', default: 'Score' },
      { name: 'difficultyLabel', type: 'text', default: 'Beginner' },
    ],
    defaultProps: { href: '#', seed: 'prelude', className: 'max-w-xs' },
  },
  {
    id: 'ui-field',
    name: 'Field',
    pkg: 'ui',
    domains: ['molecules'],
    kind: 'presentational',
    load: examples,
    exportName: 'FieldExample',
  },
  {
    id: 'ui-segmented-toggle',
    name: 'SegmentedToggle',
    pkg: 'ui',
    domains: ['molecules'],
    kind: 'interactive',
    load: examples,
    exportName: 'SegmentedToggleExample',
  },
  {
    id: 'ui-facet-panel',
    name: 'FacetPanel',
    pkg: 'ui',
    domains: ['molecules'],
    kind: 'interactive',
    load: examples,
    exportName: 'FacetPanelExample',
  },
  {
    id: 'ui-active-filters',
    name: 'ActiveFilters',
    pkg: 'ui',
    domains: ['molecules'],
    kind: 'interactive',
    load: examples,
    exportName: 'ActiveFiltersExample',
  },
  {
    id: 'ui-card-grid',
    name: 'CardGrid',
    pkg: 'ui',
    domains: ['molecules'],
    kind: 'presentational',
    load: examples,
    exportName: 'CardGridExample',
  },
  {
    id: 'ui-featured-shelf',
    name: 'FeaturedShelf',
    pkg: 'ui',
    domains: ['molecules'],
    kind: 'presentational',
    load: examples,
    exportName: 'FeaturedShelfExample',
  },
  {
    id: 'ui-form-actions',
    name: 'FormActions',
    pkg: 'ui',
    domains: ['molecules'],
    kind: 'presentational',
    load: examples,
    exportName: 'FormActionsExample',
  },
  {
    id: 'ui-tool-stage',
    name: 'ToolStage',
    pkg: 'ui',
    domains: ['molecules'],
    kind: 'interactive',
    load: examples,
    exportName: 'ToolStageExample',
  },
  {
    id: 'ui-pagination-bar',
    name: 'PaginationBar',
    pkg: 'ui',
    domains: ['molecules'],
    kind: 'interactive',
    load: examples,
    exportName: 'PaginationBarExample',
  },
];
