/** Seed dataset — public-domain / openly-licensed catalogue items + taxonomy. */

export const GENRES = [
  { slug: 'classical', name: 'Classical' },
  { slug: 'jazz', name: 'Jazz' },
  { slug: 'blues', name: 'Blues' },
  { slug: 'folk', name: 'Folk' },
  { slug: 'ragtime', name: 'Ragtime' },
  { slug: 'pop', name: 'Pop' },
  { slug: 'rock', name: 'Rock' },
  { slug: 'spiritual', name: 'Spiritual' },
];

export const INSTRUMENTS = [
  { slug: 'piano', name: 'Piano' },
  { slug: 'guitar', name: 'Guitar' },
  { slug: 'ukulele', name: 'Ukulele' },
  { slug: 'bass', name: 'Bass' },
];

export const SKILL_TOPICS = [
  { slug: 'scales', name: 'Scales' },
  { slug: 'chords', name: 'Chords' },
  { slug: 'arpeggios', name: 'Arpeggios' },
  { slug: 'sight-reading', name: 'Sight-reading' },
  { slug: 'technique', name: 'Technique' },
  { slug: 'theory', name: 'Theory' },
  { slug: 'ear-training', name: 'Ear training' },
  { slug: 'rhythm', name: 'Rhythm' },
  { slug: 'improvisation', name: 'Improvisation' },
  { slug: 'modes', name: 'Modes' },
  { slug: 'voice-leading', name: 'Voice leading' },
];

export const TAGS = [
  { slug: 'public-domain', name: 'Public domain' },
  { slug: 'beginner', name: 'Beginner' },
  { slug: 'exercise', name: 'Exercise' },
  { slug: 'intermediate', name: 'Intermediate' },
  { slug: 'cc-by-sa', name: 'CC BY-SA' },
  { slug: 'advanced', name: 'Advanced' },
];

export interface SeedContent {
  slug: string;
  title: string;
  summary: string;
  type: string;
  difficulty: number | null;
  genres: string[];
  instruments: string[];
  topics: string[];
  tags: string[];
  source: string;
  attribution: string;
  license: string;
  withPdf?: boolean;
  /** Phase 6 — `premium` gates the item behind an entitlement; defaults to `public`. */
  visibility?: string;
  /** Phase 6 (6B) — which plan unlocks a premium item: `premium` (default) or `pro`. */
  tier?: string;
}

const PD = 'Public Domain';

export const CONTENT: SeedContent[] = [
  {
    slug: 'bach-prelude-c-major-bwv-846',
    title: 'Prelude in C major, BWV 846',
    summary: 'The opening prelude of the Well-Tempered Clavier — flowing broken chords.',
    type: 'score',
    difficulty: 5,
    genres: ['classical'],
    instruments: ['piano'],
    topics: ['sight-reading', 'arpeggios'],
    tags: ['public-domain'],
    source: 'IMSLP',
    attribution: 'J. S. Bach',
    license: PD,
    withPdf: true,
  },
  {
    slug: 'hanon-virtuoso-pianist-no-1',
    title: 'The Virtuoso Pianist — Exercise No. 1',
    summary: 'Classic finger-independence exercise for the five fingers.',
    type: 'technique',
    difficulty: 3,
    genres: ['classical'],
    instruments: ['piano'],
    topics: ['technique', 'scales'],
    tags: ['public-domain', 'exercise'],
    source: 'Hanon',
    attribution: 'Charles-Louis Hanon',
    license: PD,
    withPdf: true,
  },
  {
    slug: 'czerny-op-599-no-1',
    title: 'Practical Method for Beginners, Op. 599 No. 1',
    summary: 'A gentle beginner study for evenness and hand position.',
    type: 'exercise',
    difficulty: 2,
    genres: ['classical'],
    instruments: ['piano'],
    topics: ['technique'],
    tags: ['public-domain', 'exercise', 'beginner'],
    source: 'Czerny',
    attribution: 'Carl Czerny',
    license: PD,
    visibility: 'premium',
    withPdf: true,
  },
  {
    slug: 'omt-intervals',
    title: 'Intervals',
    summary: 'How to measure and name the distance between two pitches.',
    type: 'lesson',
    difficulty: null,
    genres: [],
    instruments: [],
    topics: ['theory'],
    tags: [],
    source: 'Open Music Theory',
    attribution: 'Open Music Theory (CC BY-SA 4.0)',
    license: 'CC BY-SA 4.0',
  },
  {
    slug: 'omt-diatonic-chords',
    title: 'Diatonic Chords',
    summary: 'Building triads on each scale degree and naming them with Roman numerals.',
    type: 'lesson',
    difficulty: null,
    genres: [],
    instruments: [],
    topics: ['theory', 'chords'],
    tags: [],
    source: 'Open Music Theory',
    attribution: 'Open Music Theory (CC BY-SA 4.0)',
    license: 'CC BY-SA 4.0',
    visibility: 'premium',
    tier: 'pro',
  },
  {
    slug: 'omt-advanced-harmony-institution',
    title: 'Advanced Harmony (Institution)',
    summary: 'Chromatic harmony, modulation, and voice-leading — an institution-tier deep dive.',
    type: 'lesson',
    difficulty: null,
    genres: [],
    instruments: [],
    topics: ['theory', 'chords'],
    tags: [],
    source: 'Open Music Theory',
    attribution: 'Open Music Theory (CC BY-SA 4.0)',
    license: 'CC BY-SA 4.0',
    visibility: 'premium',
    tier: 'institution',
  },
  {
    slug: 'greensleeves-trad',
    title: 'Greensleeves',
    summary: 'A traditional English folk tune, arranged for fingerstyle guitar.',
    type: 'song',
    difficulty: 3,
    genres: ['folk'],
    instruments: ['guitar'],
    topics: ['sight-reading'],
    tags: ['public-domain'],
    source: 'Traditional',
    attribution: 'Traditional (arr. public domain)',
    license: PD,
    withPdf: true,
  },
  {
    slug: 'joplin-the-entertainer',
    title: 'The Entertainer',
    summary: 'Scott Joplin’s beloved ragtime — syncopation and a walking bass.',
    type: 'score',
    difficulty: 6,
    genres: ['ragtime', 'jazz'],
    instruments: ['piano'],
    topics: ['sight-reading'],
    tags: ['public-domain'],
    source: 'IMSLP',
    attribution: 'Scott Joplin',
    license: PD,
    withPdf: true,
  },
  {
    slug: '12-bar-blues-in-a',
    title: '12-Bar Blues in A',
    summary: 'The essential blues form: I–IV–V over twelve bars, with a turnaround.',
    type: 'lesson',
    difficulty: 2,
    genres: ['blues'],
    instruments: ['guitar'],
    topics: ['chords'],
    tags: ['beginner'],
    source: 'Original',
    attribution: 'The Music Repository',
    license: 'CC BY-SA 4.0',
  },
  {
    slug: 'c-major-scale-two-octaves',
    title: 'C Major Scale — Two Octaves',
    summary: 'Standard fingering for the two-octave C major scale, hands together.',
    type: 'exercise',
    difficulty: 1,
    genres: ['classical'],
    instruments: ['piano'],
    topics: ['scales', 'technique'],
    tags: ['beginner', 'exercise'],
    source: 'Original',
    attribution: 'The Music Repository',
    license: 'CC BY-SA 4.0',
  },
  {
    slug: 'beethoven-fur-elise-opening',
    title: 'Für Elise (opening)',
    summary: 'The famous A-minor opening section of Beethoven’s Bagatelle.',
    type: 'score',
    difficulty: 5,
    genres: ['classical'],
    instruments: ['piano'],
    topics: ['sight-reading'],
    tags: ['public-domain'],
    source: 'IMSLP',
    attribution: 'Ludwig van Beethoven',
    license: PD,
    withPdf: true,
  },
  {
    slug: 'carulli-guitar-study',
    title: 'Guitar Study in A minor',
    summary: 'A short classical-guitar study developing arpeggio technique.',
    type: 'score',
    difficulty: 3,
    genres: ['classical'],
    instruments: ['guitar'],
    topics: ['arpeggios', 'technique'],
    tags: ['public-domain'],
    source: 'IMSLP',
    attribution: 'Ferdinando Carulli',
    license: PD,
    withPdf: true,
  },
  {
    slug: 'circle-of-fifths-reference',
    title: 'Circle of Fifths — Reference',
    summary: 'Keys, signatures, and relationships at a glance.',
    type: 'tool_page',
    difficulty: null,
    genres: [],
    instruments: [],
    topics: ['theory'],
    tags: [],
    source: 'Original',
    attribution: 'The Music Repository',
    license: 'CC BY-SA 4.0',
  },
  {
    slug: 'amazing-grace-trad',
    title: 'Amazing Grace',
    summary: 'A traditional hymn — a gentle first song in G major.',
    type: 'song',
    difficulty: 2,
    genres: ['folk'],
    instruments: ['piano', 'guitar'],
    topics: ['sight-reading'],
    tags: ['public-domain', 'beginner'],
    source: 'Traditional',
    attribution: 'Traditional',
    license: PD,
  },
  {
    slug: 'chromatic-scale-exercise',
    title: 'Chromatic Scale Exercise',
    summary: 'Evenness and finger crossings across the full chromatic scale.',
    type: 'exercise',
    difficulty: 2,
    genres: ['classical'],
    instruments: ['piano'],
    topics: ['scales', 'technique'],
    tags: ['exercise'],
    source: 'Original',
    attribution: 'The Music Repository',
    license: 'CC BY-SA 4.0',
  },
  {
    slug: 'minor-pentatonic-scale-shapes',
    title: 'Minor Pentatonic Scale Shapes',
    summary: 'The five movable shapes that unlock blues and rock soloing.',
    type: 'lesson',
    difficulty: 3,
    genres: ['blues'],
    instruments: ['guitar'],
    topics: ['scales'],
    tags: [],
    source: 'Original',
    attribution: 'The Music Repository',
    license: 'CC BY-SA 4.0',
  },
  // --- Slice 3: additional catalogue depth ---
  {
    slug: 'bach-minuet-in-g',
    title: 'Minuet in G major, BWV Anh. 114',
    summary: 'A graceful early-intermediate minuet from the Notebook for Anna Magdalena Bach.',
    type: 'score',
    difficulty: 3,
    genres: ['classical'],
    instruments: ['piano'],
    topics: ['sight-reading', 'technique'],
    tags: ['public-domain'],
    source: 'IMSLP',
    attribution: 'C. Petzold (attrib. J. S. Bach)',
    license: PD,
    withPdf: true,
  },
  {
    slug: 'carcassi-guitar-study-op60-no1',
    title: 'Study in C major, Op. 60 No. 1',
    summary: 'A flowing classical-guitar study building right-hand arpeggio control.',
    type: 'score',
    difficulty: 4,
    genres: ['classical'],
    instruments: ['guitar'],
    topics: ['arpeggios', 'technique'],
    tags: ['public-domain', 'intermediate'],
    source: 'IMSLP',
    attribution: 'Matteo Carcassi',
    license: PD,
    withPdf: true,
  },
  {
    slug: 'joplin-maple-leaf-rag',
    title: 'Maple Leaf Rag',
    summary: "Scott Joplin's landmark rag — driving syncopation over a steady stride bass.",
    type: 'score',
    difficulty: 7,
    genres: ['ragtime', 'jazz'],
    instruments: ['piano'],
    topics: ['rhythm', 'sight-reading'],
    tags: ['public-domain'],
    source: 'IMSLP',
    attribution: 'Scott Joplin',
    license: PD,
    withPdf: true,
  },
  {
    slug: 'ukulele-first-four-chords',
    title: 'Your First Four Ukulele Chords',
    summary: 'C, G, Am, and F — enough to play dozens of songs on the ukulele.',
    type: 'lesson',
    difficulty: 1,
    genres: ['pop', 'folk'],
    instruments: ['ukulele'],
    topics: ['chords'],
    tags: ['beginner'],
    source: 'Original',
    attribution: 'The Music Repository',
    license: 'CC BY-SA 4.0',
  },
  {
    slug: 'walking-bass-basics',
    title: 'Walking Bass Basics',
    summary: 'Build a smooth quarter-note walking line over a ii–V–I in jazz.',
    type: 'lesson',
    difficulty: 4,
    genres: ['jazz'],
    instruments: ['bass'],
    topics: ['improvisation', 'rhythm'],
    tags: ['intermediate'],
    source: 'Original',
    attribution: 'The Music Repository',
    license: 'CC BY-SA 4.0',
  },
  {
    slug: 'blues-scale-piano',
    title: 'The Blues Scale at the Piano',
    summary: 'The six-note blues scale and how to use it for expressive soloing.',
    type: 'lesson',
    difficulty: 3,
    genres: ['blues'],
    instruments: ['piano'],
    topics: ['scales', 'improvisation'],
    tags: [],
    source: 'Original',
    attribution: 'The Music Repository',
    license: 'CC BY-SA 4.0',
  },
  {
    slug: 'omt-rhythm-and-meter',
    title: 'Rhythm and Meter',
    summary: 'Beats, measures, and time signatures — how music is organised in time.',
    type: 'lesson',
    difficulty: null,
    genres: [],
    instruments: [],
    topics: ['theory', 'rhythm'],
    tags: ['cc-by-sa'],
    source: 'Open Music Theory',
    attribution: 'Open Music Theory (CC BY-SA 4.0)',
    license: 'CC BY-SA 4.0',
  },
  {
    slug: 'omt-modes-of-major',
    title: 'Modes of the Major Scale',
    summary: 'Ionian to Locrian — the seven modes and their characteristic colours.',
    type: 'lesson',
    difficulty: null,
    genres: [],
    instruments: [],
    topics: ['theory', 'modes', 'scales'],
    tags: ['cc-by-sa'],
    source: 'Open Music Theory',
    attribution: 'Open Music Theory (CC BY-SA 4.0)',
    license: 'CC BY-SA 4.0',
  },
  {
    slug: 'interval-ear-training-primer',
    title: 'Interval Ear-Training Primer',
    summary: 'Recognise intervals by ear using familiar-song reference points.',
    type: 'exercise',
    difficulty: 2,
    genres: [],
    instruments: [],
    topics: ['ear-training', 'theory'],
    tags: ['beginner'],
    source: 'Original',
    attribution: 'The Music Repository',
    license: 'CC BY-SA 4.0',
  },
  {
    slug: 'major-scales-all-keys',
    title: 'Major Scales in All Keys',
    summary: 'Standard fingering for major scales around the circle of fifths.',
    type: 'exercise',
    difficulty: 4,
    genres: ['classical'],
    instruments: ['piano'],
    topics: ['scales', 'technique'],
    tags: ['exercise'],
    source: 'Original',
    attribution: 'The Music Repository',
    license: 'CC BY-SA 4.0',
  },
  // --- Catalogue expansion: piano classical ---
  {
    slug: 'beethoven-moonlight-sonata-1st-mvt',
    title: 'Moonlight Sonata, Op. 27 No. 2 — I. Adagio sostenuto',
    summary: 'The hushed, arpeggiated first movement of Beethoven’s Sonata quasi una fantasia.',
    type: 'score',
    difficulty: 6,
    genres: ['classical'],
    instruments: ['piano'],
    topics: ['arpeggios', 'sight-reading'],
    tags: ['public-domain', 'intermediate'],
    source: 'IMSLP',
    attribution: 'Ludwig van Beethoven',
    license: PD,
    withPdf: true,
    visibility: 'premium',
    tier: 'premium',
  },
  {
    slug: 'beethoven-ode-to-joy',
    title: 'Ode to Joy (Symphony No. 9 theme)',
    summary: 'Beethoven’s famous choral theme, arranged as a simple first melody.',
    type: 'song',
    difficulty: 1,
    genres: ['classical'],
    instruments: ['piano'],
    topics: ['sight-reading'],
    tags: ['public-domain', 'beginner'],
    source: 'IMSLP',
    attribution: 'Ludwig van Beethoven',
    license: PD,
    withPdf: true,
  },
  {
    slug: 'beethoven-sonatina-in-g-anh5',
    title: 'Sonatina in G major, Anh. 5 No. 1',
    summary: 'A cheerful two-movement sonatina long attributed to Beethoven.',
    type: 'score',
    difficulty: 4,
    genres: ['classical'],
    instruments: ['piano'],
    topics: ['sight-reading', 'technique'],
    tags: ['public-domain', 'intermediate'],
    source: 'IMSLP',
    attribution: 'attrib. Ludwig van Beethoven',
    license: PD,
    withPdf: true,
  },
  {
    slug: 'mozart-minuet-in-f-k2',
    title: 'Minuet in F major, K. 2',
    summary: 'A short, elegant minuet composed by Mozart as a child.',
    type: 'score',
    difficulty: 3,
    genres: ['classical'],
    instruments: ['piano'],
    topics: ['sight-reading', 'technique'],
    tags: ['public-domain'],
    source: 'IMSLP',
    attribution: 'Wolfgang Amadeus Mozart',
    license: PD,
    withPdf: true,
  },
  {
    slug: 'mozart-sonata-k545-1st-mvt',
    title: 'Piano Sonata No. 16 in C, K. 545 — I. Allegro',
    summary: 'The “Sonata facile” first movement — clear textures and classic Alberti bass.',
    type: 'score',
    difficulty: 6,
    genres: ['classical'],
    instruments: ['piano'],
    topics: ['scales', 'sight-reading'],
    tags: ['public-domain', 'intermediate'],
    source: 'IMSLP',
    attribution: 'Wolfgang Amadeus Mozart',
    license: PD,
    withPdf: true,
  },
  {
    slug: 'chopin-prelude-e-minor-op28-no4',
    title: 'Prelude in E minor, Op. 28 No. 4',
    summary: 'A melancholy prelude over slowly shifting chords — deceptively expressive.',
    type: 'score',
    difficulty: 5,
    genres: ['classical'],
    instruments: ['piano'],
    topics: ['sight-reading', 'chords'],
    tags: ['public-domain', 'intermediate'],
    source: 'IMSLP',
    attribution: 'Frédéric Chopin',
    license: PD,
    withPdf: true,
  },
  {
    slug: 'chopin-nocturne-op9-no2',
    title: 'Nocturne in E-flat major, Op. 9 No. 2',
    summary: 'Chopin’s most beloved nocturne — an ornamented, singing right-hand line.',
    type: 'score',
    difficulty: 7,
    genres: ['classical'],
    instruments: ['piano'],
    topics: ['sight-reading', 'technique'],
    tags: ['public-domain', 'advanced'],
    source: 'IMSLP',
    attribution: 'Frédéric Chopin',
    license: PD,
    withPdf: true,
    visibility: 'premium',
    tier: 'pro',
  },
  {
    slug: 'chopin-waltz-a-minor-b150',
    title: 'Waltz in A minor, B. 150',
    summary: 'A gentle, wistful posthumous waltz — accessible late-intermediate Chopin.',
    type: 'score',
    difficulty: 4,
    genres: ['classical'],
    instruments: ['piano'],
    topics: ['sight-reading', 'rhythm'],
    tags: ['public-domain', 'intermediate'],
    source: 'IMSLP',
    attribution: 'Frédéric Chopin',
    license: PD,
    withPdf: true,
  },
  {
    slug: 'schumann-the-wild-horseman-op68',
    title: 'The Wild Horseman, Op. 68 No. 8',
    summary: 'A galloping character piece from Schumann’s Album for the Young.',
    type: 'score',
    difficulty: 3,
    genres: ['classical'],
    instruments: ['piano'],
    topics: ['rhythm', 'technique'],
    tags: ['public-domain'],
    source: 'IMSLP',
    attribution: 'Robert Schumann',
    license: PD,
    withPdf: true,
  },
  {
    slug: 'schumann-melody-op68-no1',
    title: 'Melody, Op. 68 No. 1',
    summary: 'The gentle opening piece of the Album for the Young — a first singing melody.',
    type: 'score',
    difficulty: 2,
    genres: ['classical'],
    instruments: ['piano'],
    topics: ['sight-reading'],
    tags: ['public-domain', 'beginner'],
    source: 'IMSLP',
    attribution: 'Robert Schumann',
    license: PD,
    withPdf: true,
  },
  {
    slug: 'clementi-sonatina-op36-no1-1st-mvt',
    title: 'Sonatina in C, Op. 36 No. 1 — I. Allegro',
    summary: 'The classic student sonatina — crisp scales and a tidy Classical form.',
    type: 'score',
    difficulty: 4,
    genres: ['classical'],
    instruments: ['piano'],
    topics: ['scales', 'sight-reading'],
    tags: ['public-domain', 'intermediate'],
    source: 'IMSLP',
    attribution: 'Muzio Clementi',
    license: PD,
    withPdf: true,
  },
  {
    slug: 'kuhlau-sonatina-op20-no1-1st-mvt',
    title: 'Sonatina in C, Op. 20 No. 1 — I. Allegro',
    summary: 'A bright, idiomatic Kuhlau sonatina movement for developing pianists.',
    type: 'score',
    difficulty: 5,
    genres: ['classical'],
    instruments: ['piano'],
    topics: ['scales', 'technique'],
    tags: ['public-domain', 'intermediate'],
    source: 'IMSLP',
    attribution: 'Friedrich Kuhlau',
    license: PD,
    withPdf: true,
  },
  {
    slug: 'burgmuller-arabesque-op100-no2',
    title: 'Arabesque, Op. 100 No. 2',
    summary: 'A sparkling study in fingerwork and phrasing from Burgmüller’s 25 Études.',
    type: 'score',
    difficulty: 3,
    genres: ['classical'],
    instruments: ['piano'],
    topics: ['technique', 'sight-reading'],
    tags: ['public-domain'],
    source: 'IMSLP',
    attribution: 'Friedrich Burgmüller',
    license: PD,
    withPdf: true,
  },
  {
    slug: 'burgmuller-la-candeur-op100-no1',
    title: 'La Candeur (Frankness), Op. 100 No. 1',
    summary: 'A flowing, even-toned study opening Burgmüller’s progressive études.',
    type: 'score',
    difficulty: 3,
    genres: ['classical'],
    instruments: ['piano'],
    topics: ['technique'],
    tags: ['public-domain'],
    source: 'IMSLP',
    attribution: 'Friedrich Burgmüller',
    license: PD,
    withPdf: true,
  },
  {
    slug: 'schubert-ave-maria',
    title: 'Ave Maria (Ellens dritter Gesang)',
    summary: 'Schubert’s serene song, arranged for solo piano.',
    type: 'song',
    difficulty: 5,
    genres: ['classical'],
    instruments: ['piano'],
    topics: ['sight-reading'],
    tags: ['public-domain', 'intermediate'],
    source: 'IMSLP',
    attribution: 'Franz Schubert',
    license: PD,
    withPdf: true,
  },
  {
    slug: 'schubert-landler-d366',
    title: 'Ländler in B-flat, D. 366',
    summary: 'A short, dance-like Ländler — a friendly first taste of Schubert.',
    type: 'score',
    difficulty: 2,
    genres: ['classical'],
    instruments: ['piano'],
    topics: ['rhythm', 'sight-reading'],
    tags: ['public-domain', 'beginner'],
    source: 'IMSLP',
    attribution: 'Franz Schubert',
    license: PD,
    withPdf: true,
  },
  {
    slug: 'satie-gymnopedie-no1',
    title: 'Gymnopédie No. 1',
    summary: 'Satie’s dreamlike, slow waltz — spare textures and gentle dissonance.',
    type: 'score',
    difficulty: 4,
    genres: ['classical'],
    instruments: ['piano'],
    topics: ['sight-reading', 'chords'],
    tags: ['public-domain', 'intermediate'],
    source: 'IMSLP',
    attribution: 'Erik Satie',
    license: PD,
    withPdf: true,
  },
  {
    slug: 'satie-gnossienne-no1',
    title: 'Gnossienne No. 1',
    summary: 'A hypnotic, free-metered piece with modal colour and rubato.',
    type: 'score',
    difficulty: 6,
    genres: ['classical'],
    instruments: ['piano'],
    topics: ['modes', 'sight-reading'],
    tags: ['public-domain', 'advanced'],
    source: 'IMSLP',
    attribution: 'Erik Satie',
    license: PD,
    withPdf: true,
    visibility: 'premium',
    tier: 'premium',
  },
  {
    slug: 'debussy-clair-de-lune',
    title: 'Clair de Lune (Suite bergamasque)',
    summary: 'Debussy’s luminous impressionist masterpiece — subtle voicing and pedalling.',
    type: 'score',
    difficulty: 8,
    genres: ['classical'],
    instruments: ['piano'],
    topics: ['technique', 'sight-reading'],
    tags: ['public-domain', 'advanced'],
    source: 'IMSLP',
    attribution: 'Claude Debussy',
    license: PD,
    withPdf: true,
    visibility: 'premium',
    tier: 'pro',
  },
  {
    slug: 'debussy-arabesque-no1',
    title: 'Première Arabesque',
    summary: 'Rippling arpeggios and cross-rhythms in Debussy’s early impressionist gem.',
    type: 'score',
    difficulty: 7,
    genres: ['classical'],
    instruments: ['piano'],
    topics: ['arpeggios', 'rhythm'],
    tags: ['public-domain', 'advanced'],
    source: 'IMSLP',
    attribution: 'Claude Debussy',
    license: PD,
    withPdf: true,
  },
  {
    slug: 'bach-invention-no1-bwv772',
    title: 'Invention No. 1 in C major, BWV 772',
    summary: 'A two-voice keyboard invention — essential training in independent hands.',
    type: 'score',
    difficulty: 5,
    genres: ['classical'],
    instruments: ['piano'],
    topics: ['technique', 'sight-reading'],
    tags: ['public-domain', 'intermediate'],
    source: 'IMSLP',
    attribution: 'J. S. Bach',
    license: PD,
    withPdf: true,
  },
  // --- Ragtime ---
  {
    slug: 'joplin-pineapple-rag',
    title: 'Pineapple Rag',
    summary: 'A tuneful, swinging Joplin rag with an infectious second strain.',
    type: 'score',
    difficulty: 7,
    genres: ['ragtime', 'jazz'],
    instruments: ['piano'],
    topics: ['rhythm', 'sight-reading'],
    tags: ['public-domain', 'advanced'],
    source: 'IMSLP',
    attribution: 'Scott Joplin',
    license: PD,
    withPdf: true,
  },
  {
    slug: 'joplin-solace',
    title: 'Solace — A Mexican Serenade',
    summary: 'A lyrical habanera-flavoured piece by Joplin, gentler than his stride rags.',
    type: 'score',
    difficulty: 6,
    genres: ['ragtime'],
    instruments: ['piano'],
    topics: ['rhythm', 'sight-reading'],
    tags: ['public-domain', 'intermediate'],
    source: 'IMSLP',
    attribution: 'Scott Joplin',
    license: PD,
    withPdf: true,
  },
  {
    slug: 'joplin-ragtime-dance',
    title: 'The Ragtime Dance',
    summary: 'A stomping, sectional Joplin dance number full of syncopated energy.',
    type: 'score',
    difficulty: 6,
    genres: ['ragtime'],
    instruments: ['piano'],
    topics: ['rhythm'],
    tags: ['public-domain', 'intermediate'],
    source: 'IMSLP',
    attribution: 'Scott Joplin',
    license: PD,
    withPdf: true,
  },
  {
    slug: 'lamb-american-beauty-rag',
    title: 'American Beauty Rag',
    summary: 'A refined, richly harmonised “classic rag” by Joseph Lamb.',
    type: 'score',
    difficulty: 8,
    genres: ['ragtime'],
    instruments: ['piano'],
    topics: ['rhythm', 'technique'],
    tags: ['public-domain', 'advanced'],
    source: 'IMSLP',
    attribution: 'Joseph Lamb',
    license: PD,
    withPdf: true,
  },
  {
    slug: 'scott-frog-legs-rag',
    title: 'Frog Legs Rag',
    summary: 'A brilliant, cascading rag by James Scott — one of the era’s finest.',
    type: 'score',
    difficulty: 7,
    genres: ['ragtime'],
    instruments: ['piano'],
    topics: ['rhythm', 'technique'],
    tags: ['public-domain', 'advanced'],
    source: 'IMSLP',
    attribution: 'James Scott',
    license: PD,
    withPdf: true,
  },
  // --- Blues / early jazz ---
  {
    slug: 'handy-st-louis-blues',
    title: 'St. Louis Blues',
    summary: 'W. C. Handy’s landmark 1914 blues — a habanera strain meets the 12-bar form.',
    type: 'song',
    difficulty: 4,
    genres: ['blues', 'jazz'],
    instruments: ['piano'],
    topics: ['chords', 'improvisation'],
    tags: ['public-domain', 'intermediate'],
    source: 'IMSLP',
    attribution: 'W. C. Handy',
    license: PD,
    withPdf: true,
  },
  {
    slug: 'frankie-and-johnny',
    title: 'Frankie and Johnny',
    summary: 'A traditional American blues ballad — a great vehicle for 12-bar phrasing.',
    type: 'song',
    difficulty: 3,
    genres: ['blues', 'folk'],
    instruments: ['guitar', 'piano'],
    topics: ['chords'],
    tags: ['public-domain'],
    source: 'Traditional',
    attribution: 'Traditional',
    license: PD,
    withPdf: true,
  },
  // --- Traditional / folk ---
  {
    slug: 'scarborough-fair',
    title: 'Scarborough Fair',
    summary: 'A haunting Dorian-mode English ballad, arranged for fingerstyle guitar.',
    type: 'song',
    difficulty: 3,
    genres: ['folk'],
    instruments: ['guitar'],
    topics: ['modes', 'sight-reading'],
    tags: ['public-domain'],
    source: 'Traditional',
    attribution: 'Traditional (arr. public domain)',
    license: PD,
    withPdf: true,
  },
  {
    slug: 'danny-boy',
    title: 'Danny Boy (Londonderry Air)',
    summary: 'The beloved Irish air, set as a lyrical melody with simple accompaniment.',
    type: 'song',
    difficulty: 3,
    genres: ['folk'],
    instruments: ['piano', 'guitar'],
    topics: ['sight-reading'],
    tags: ['public-domain'],
    source: 'Traditional',
    attribution: 'Traditional',
    license: PD,
    withPdf: true,
  },
  {
    slug: 'house-of-the-rising-sun',
    title: 'House of the Rising Sun',
    summary: 'A traditional folk tune in 6/8 — perfect for arpeggiated guitar chords.',
    type: 'song',
    difficulty: 2,
    genres: ['folk'],
    instruments: ['guitar'],
    topics: ['arpeggios', 'chords'],
    tags: ['public-domain', 'beginner'],
    source: 'Traditional',
    attribution: 'Traditional',
    license: PD,
    withPdf: true,
  },
  {
    slug: 'shenandoah',
    title: 'Shenandoah',
    summary: 'A gentle American river song — a favourite for legato phrasing.',
    type: 'song',
    difficulty: 2,
    genres: ['folk'],
    instruments: ['piano', 'guitar'],
    topics: ['sight-reading'],
    tags: ['public-domain', 'beginner'],
    source: 'Traditional',
    attribution: 'Traditional',
    license: PD,
    withPdf: true,
  },
  {
    slug: 'wildwood-flower',
    title: 'Wildwood Flower',
    summary: 'An Appalachian classic and a rite of passage for flatpicking guitarists.',
    type: 'song',
    difficulty: 2,
    genres: ['folk'],
    instruments: ['guitar'],
    topics: ['technique', 'sight-reading'],
    tags: ['public-domain', 'beginner'],
    source: 'Traditional',
    attribution: 'Traditional',
    license: PD,
    withPdf: true,
  },
  {
    slug: 'simple-gifts',
    title: 'Simple Gifts',
    summary: 'The Shaker melody made famous by Copland — a clean, singable tune.',
    type: 'song',
    difficulty: 2,
    genres: ['folk'],
    instruments: ['piano', 'ukulele'],
    topics: ['sight-reading'],
    tags: ['public-domain', 'beginner'],
    source: 'Traditional',
    attribution: 'Traditional (Joseph Brackett)',
    license: PD,
    withPdf: true,
  },
  // --- Spirituals ---
  {
    slug: 'swing-low-sweet-chariot',
    title: 'Swing Low, Sweet Chariot',
    summary: 'A traditional spiritual with a warm, call-and-response feel.',
    type: 'song',
    difficulty: 2,
    genres: ['spiritual', 'folk'],
    instruments: ['piano', 'guitar'],
    topics: ['sight-reading'],
    tags: ['public-domain', 'beginner'],
    source: 'Traditional',
    attribution: 'Traditional (spiritual)',
    license: PD,
    withPdf: true,
  },
  {
    slug: 'when-the-saints-go-marching-in',
    title: 'When the Saints Go Marching In',
    summary: 'The New Orleans standard — an easy, joyful first tune in any key.',
    type: 'song',
    difficulty: 1,
    genres: ['spiritual', 'jazz'],
    instruments: ['piano', 'ukulele'],
    topics: ['sight-reading', 'chords'],
    tags: ['public-domain', 'beginner'],
    source: 'Traditional',
    attribution: 'Traditional (spiritual)',
    license: PD,
    withPdf: true,
  },
  // --- Classical guitar studies ---
  {
    slug: 'sor-study-op60-no1',
    title: 'Study in C major, Op. 60 No. 1',
    summary: 'A gentle beginner study from Sor’s progressive guitar method.',
    type: 'score',
    difficulty: 2,
    genres: ['classical'],
    instruments: ['guitar'],
    topics: ['technique', 'sight-reading'],
    tags: ['public-domain', 'beginner'],
    source: 'IMSLP',
    attribution: 'Fernando Sor',
    license: PD,
    withPdf: true,
  },
  {
    slug: 'sor-study-op35-no22',
    title: 'Study in B minor, Op. 35 No. 22',
    summary: 'The famous “Segovia” study — a singing melody over rolling accompaniment.',
    type: 'score',
    difficulty: 5,
    genres: ['classical'],
    instruments: ['guitar'],
    topics: ['arpeggios', 'technique'],
    tags: ['public-domain', 'intermediate'],
    source: 'IMSLP',
    attribution: 'Fernando Sor',
    license: PD,
    withPdf: true,
  },
  {
    slug: 'carcassi-study-op60-no7',
    title: 'Study in A minor, Op. 60 No. 7',
    summary: 'A flowing arpeggio study developing right-hand fluency.',
    type: 'score',
    difficulty: 5,
    genres: ['classical'],
    instruments: ['guitar'],
    topics: ['arpeggios', 'technique'],
    tags: ['public-domain', 'intermediate'],
    source: 'IMSLP',
    attribution: 'Matteo Carcassi',
    license: PD,
    withPdf: true,
  },
  {
    slug: 'tarrega-lagrima',
    title: 'Lágrima',
    summary: 'A short, tender prelude by Tárrega — a beloved first Romantic study.',
    type: 'score',
    difficulty: 4,
    genres: ['classical'],
    instruments: ['guitar'],
    topics: ['technique', 'sight-reading'],
    tags: ['public-domain', 'intermediate'],
    source: 'IMSLP',
    attribution: 'Francisco Tárrega',
    license: PD,
    withPdf: true,
  },
  {
    slug: 'tarrega-adelita',
    title: 'Adelita (Mazurka)',
    summary: 'An expressive miniature mazurka rich in rubato and dynamic shading.',
    type: 'score',
    difficulty: 5,
    genres: ['classical'],
    instruments: ['guitar'],
    topics: ['technique', 'rhythm'],
    tags: ['public-domain', 'intermediate'],
    source: 'IMSLP',
    attribution: 'Francisco Tárrega',
    license: PD,
    withPdf: true,
  },
  {
    slug: 'tarrega-recuerdos-de-la-alhambra',
    title: 'Recuerdos de la Alhambra',
    summary: 'Tárrega’s tremolo masterpiece — a shimmering study in right-hand control.',
    type: 'score',
    difficulty: 9,
    genres: ['classical'],
    instruments: ['guitar'],
    topics: ['technique', 'arpeggios'],
    tags: ['public-domain', 'advanced'],
    source: 'IMSLP',
    attribution: 'Francisco Tárrega',
    license: PD,
    withPdf: true,
    visibility: 'premium',
    tier: 'pro',
  },
  {
    slug: 'carulli-andante-op241',
    title: 'Andante in C, Op. 241',
    summary: 'A graceful, melodic study for the developing classical guitarist.',
    type: 'score',
    difficulty: 3,
    genres: ['classical'],
    instruments: ['guitar'],
    topics: ['sight-reading', 'technique'],
    tags: ['public-domain'],
    source: 'IMSLP',
    attribution: 'Ferdinando Carulli',
    license: PD,
    withPdf: true,
  },
  // --- Ukulele ---
  {
    slug: 'ukulele-strumming-patterns',
    title: 'Essential Ukulele Strumming Patterns',
    summary: 'Down-up patterns and the island strum to bring your chords to life.',
    type: 'lesson',
    difficulty: 2,
    genres: ['pop', 'folk'],
    instruments: ['ukulele'],
    topics: ['rhythm', 'technique'],
    tags: ['beginner'],
    source: 'Original',
    attribution: 'The Music Repository',
    license: 'CC BY-SA 4.0',
  },
  {
    slug: 'ukulele-fingerpicking-primer',
    title: 'Ukulele Fingerpicking Primer',
    summary: 'A first look at thumb-and-fingers patterns for melodic ukulele playing.',
    type: 'lesson',
    difficulty: 3,
    genres: ['folk'],
    instruments: ['ukulele'],
    topics: ['technique', 'arpeggios'],
    tags: ['intermediate'],
    source: 'Original',
    attribution: 'The Music Repository',
    license: 'CC BY-SA 4.0',
  },
  {
    slug: 'ukulele-major-scale-shapes',
    title: 'Ukulele Major Scale Shapes',
    summary: 'Movable major-scale fingerings across the ukulele fretboard.',
    type: 'exercise',
    difficulty: 2,
    genres: ['folk'],
    instruments: ['ukulele'],
    topics: ['scales', 'technique'],
    tags: ['beginner', 'exercise'],
    source: 'Original',
    attribution: 'The Music Repository',
    license: 'CC BY-SA 4.0',
    withPdf: true,
  },
  {
    slug: 'aloha-oe-ukulele',
    title: 'Aloha ʻOe',
    summary: 'Queen Liliʻuokalani’s Hawaiian farewell song, arranged for ukulele.',
    type: 'song',
    difficulty: 3,
    genres: ['folk'],
    instruments: ['ukulele'],
    topics: ['chords', 'sight-reading'],
    tags: ['public-domain'],
    source: 'Traditional',
    attribution: 'Queen Liliʻuokalani',
    license: PD,
    withPdf: true,
  },
  // --- Bass ---
  {
    slug: 'bass-root-fifth-patterns',
    title: 'Root–Fifth Bass Patterns',
    summary: 'The foundation of countless songs — locking roots and fifths to the beat.',
    type: 'lesson',
    difficulty: 1,
    genres: ['pop', 'rock'],
    instruments: ['bass'],
    topics: ['rhythm', 'technique'],
    tags: ['beginner'],
    source: 'Original',
    attribution: 'The Music Repository',
    license: 'CC BY-SA 4.0',
  },
  {
    slug: 'bass-major-scale-fingerings',
    title: 'Bass Major Scale Fingerings',
    summary: 'One-octave and two-octave major-scale shapes for electric bass.',
    type: 'exercise',
    difficulty: 2,
    genres: ['classical'],
    instruments: ['bass'],
    topics: ['scales', 'technique'],
    tags: ['beginner', 'exercise'],
    source: 'Original',
    attribution: 'The Music Repository',
    license: 'CC BY-SA 4.0',
    withPdf: true,
  },
  {
    slug: 'bass-blues-line-basics',
    title: 'Building a Blues Bass Line',
    summary: 'Turn a 12-bar progression into a driving blues bass line.',
    type: 'lesson',
    difficulty: 3,
    genres: ['blues'],
    instruments: ['bass'],
    topics: ['improvisation', 'rhythm'],
    tags: ['intermediate'],
    source: 'Original',
    attribution: 'The Music Repository',
    license: 'CC BY-SA 4.0',
  },
  {
    slug: 'bass-slap-technique-intro',
    title: 'Introduction to Slap Bass',
    summary: 'Thumb slaps and finger pops — the percussive core of funk bass.',
    type: 'technique',
    difficulty: 4,
    genres: ['rock'],
    instruments: ['bass'],
    topics: ['technique', 'rhythm'],
    tags: ['intermediate'],
    source: 'Original',
    attribution: 'The Music Repository',
    license: 'CC BY-SA 4.0',
  },
  // --- Theory (Open Music Theory, CC BY-SA) ---
  {
    slug: 'omt-major-scale-key-signatures',
    title: 'The Major Scale and Key Signatures',
    summary: 'How the major scale generates each key signature around the circle of fifths.',
    type: 'lesson',
    difficulty: null,
    genres: [],
    instruments: [],
    topics: ['theory', 'scales'],
    tags: ['cc-by-sa'],
    source: 'Open Music Theory',
    attribution: 'Open Music Theory (CC BY-SA 4.0)',
    license: 'CC BY-SA 4.0',
  },
  {
    slug: 'omt-cadences',
    title: 'Cadences',
    summary: 'Authentic, plagal, half, and deceptive cadences — how phrases come to rest.',
    type: 'lesson',
    difficulty: null,
    genres: [],
    instruments: [],
    topics: ['theory', 'chords'],
    tags: ['cc-by-sa'],
    source: 'Open Music Theory',
    attribution: 'Open Music Theory (CC BY-SA 4.0)',
    license: 'CC BY-SA 4.0',
  },
  {
    slug: 'omt-seventh-chords',
    title: 'Seventh Chords',
    summary: 'The five common seventh-chord qualities and how to spell them.',
    type: 'lesson',
    difficulty: null,
    genres: [],
    instruments: [],
    topics: ['theory', 'chords'],
    tags: ['cc-by-sa'],
    source: 'Open Music Theory',
    attribution: 'Open Music Theory (CC BY-SA 4.0)',
    license: 'CC BY-SA 4.0',
  },
  {
    slug: 'omt-triads-and-inversions',
    title: 'Triads and Inversions',
    summary: 'Root position, first, and second inversion — and how to label figured bass.',
    type: 'lesson',
    difficulty: null,
    genres: [],
    instruments: [],
    topics: ['theory', 'chords'],
    tags: ['cc-by-sa'],
    source: 'Open Music Theory',
    attribution: 'Open Music Theory (CC BY-SA 4.0)',
    license: 'CC BY-SA 4.0',
  },
  {
    slug: 'omt-voice-leading',
    title: 'Voice-Leading Principles',
    summary: 'Smooth part-writing: contrary motion, resolving tendency tones, avoiding parallels.',
    type: 'lesson',
    difficulty: null,
    genres: [],
    instruments: [],
    topics: ['theory', 'voice-leading'],
    tags: ['cc-by-sa'],
    source: 'Open Music Theory',
    attribution: 'Open Music Theory (CC BY-SA 4.0)',
    license: 'CC BY-SA 4.0',
  },
  {
    slug: 'omt-secondary-dominants',
    title: 'Secondary Dominants',
    summary: 'Tonicising other scale degrees with V/x chords for richer harmony.',
    type: 'lesson',
    difficulty: null,
    genres: [],
    instruments: [],
    topics: ['theory', 'chords'],
    tags: ['cc-by-sa'],
    source: 'Open Music Theory',
    attribution: 'Open Music Theory (CC BY-SA 4.0)',
    license: 'CC BY-SA 4.0',
    visibility: 'premium',
    tier: 'pro',
  },
];

export interface SeedCollection {
  slug: string;
  title: string;
  summary: string;
  kind: string;
  itemSlugs: string[];
}

/** Ordered learning collections (Phase 2), referencing seeded content slugs. */
export const COLLECTIONS: SeedCollection[] = [
  {
    slug: 'piano-fundamentals',
    title: 'Piano Fundamentals',
    summary: 'A beginner path from your first scale to your first recital pieces.',
    kind: 'course',
    itemSlugs: [
      'c-major-scale-two-octaves',
      'czerny-op-599-no-1',
      'hanon-virtuoso-pianist-no-1',
      'bach-minuet-in-g',
      'beethoven-fur-elise-opening',
    ],
  },
  {
    slug: 'blues-starter-path',
    title: 'Blues Starter Path',
    summary: 'Start playing the blues on piano and guitar.',
    kind: 'path',
    itemSlugs: ['12-bar-blues-in-a', 'blues-scale-piano', 'minor-pentatonic-scale-shapes'],
  },
  {
    slug: 'music-theory-basics',
    title: 'Music Theory Basics',
    summary: 'The core concepts every musician should know.',
    kind: 'syllabus',
    itemSlugs: [
      'omt-intervals',
      'omt-diatonic-chords',
      'omt-rhythm-and-meter',
      'omt-modes-of-major',
    ],
  },
];

export interface SeedHelpTopic {
  slug: string;
  term: string;
  body: string;
  linkSlug?: string;
}

/** Info View help topics. Slugs match `skill_topic` slugs so topic chips resolve directly. */
export const HELP_TOPICS: SeedHelpTopic[] = [
  {
    slug: 'scales',
    term: 'Scale',
    body: 'A **scale** is an ordered set of notes spanning an octave — the raw material of melody and technique.',
    linkSlug: 'c-major-scale-two-octaves',
  },
  {
    slug: 'chords',
    term: 'Chord',
    body: 'A **chord** is three or more notes sounded together; triads (three notes) are the most common.',
    linkSlug: 'omt-diatonic-chords',
  },
  {
    slug: 'arpeggios',
    term: 'Arpeggio',
    body: 'An **arpeggio** is a chord played one note at a time rather than all at once ("broken chord").',
  },
  {
    slug: 'sight-reading',
    term: 'Sight-reading',
    body: 'Playing music **at first sight** from notation, without prior practice.',
  },
  {
    slug: 'technique',
    term: 'Technique',
    body: 'The physical skills — finger independence, evenness, hand position — that let you play freely.',
  },
  {
    slug: 'theory',
    term: 'Music theory',
    body: 'The study of how music works: pitch, rhythm, harmony, and form.',
    linkSlug: 'omt-intervals',
  },
  {
    slug: 'ear-training',
    term: 'Ear training',
    body: 'Learning to **recognise** intervals, chords, and rhythms by ear.',
    linkSlug: 'interval-ear-training-primer',
  },
  {
    slug: 'rhythm',
    term: 'Rhythm',
    body: 'How music is organised **in time** — beats, measures, and time signatures.',
    linkSlug: 'omt-rhythm-and-meter',
  },
  {
    slug: 'improvisation',
    term: 'Improvisation',
    body: 'Creating music **spontaneously**, often over a chord progression or scale.',
  },
  {
    slug: 'modes',
    term: 'Modes',
    body: 'The seven scales (Ionian…Locrian) built by starting the major scale on each of its degrees.',
    linkSlug: 'omt-modes-of-major',
  },
];

/** Build a small but valid single-page PDF (with a correct xref) titled with the given text. */
export function makeMinimalPdf(title: string): Uint8Array {
  const safe = title.replace(/[()\\]/g, ' ');
  const stream = `BT /F1 20 Tf 64 720 Td (${safe}) Tj 0 -28 Td /F1 12 Tf (The Music Repository - sample score) Tj ET`;
  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>',
    `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`,
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
  ];

  let pdf = '%PDF-1.4\n';
  const offsets: number[] = [];
  objects.forEach((obj, index) => {
    offsets.push(pdf.length);
    pdf += `${index + 1} 0 obj\n${obj}\nendobj\n`;
  });
  const xrefStart = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (const offset of offsets) {
    pdf += `${offset.toString().padStart(10, '0')} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF`;
  return new TextEncoder().encode(pdf);
}
